# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/wu/__PYNQ__/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m00_regslice_14/base_m00_regslice_14.xci
# IP: The module: 'base_m00_regslice_14' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/wu/__PYNQ__/boards/Pynq-Z2/base/base/base.gen/sources_1/bd/base/ip/base_m00_regslice_14/base_m00_regslice_14_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_m00_regslice_14'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/wu/__PYNQ__/boards/Pynq-Z2/base/base/base.gen/sources_1/bd/base/ip/base_m00_regslice_14/base_m00_regslice_14_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_m00_regslice_14'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/wu/__PYNQ__/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_m00_regslice_14/base_m00_regslice_14.xci
# IP: The module: 'base_m00_regslice_14' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/wu/__PYNQ__/boards/Pynq-Z2/base/base/base.gen/sources_1/bd/base/ip/base_m00_regslice_14/base_m00_regslice_14_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_m00_regslice_14'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/wu/__PYNQ__/boards/Pynq-Z2/base/base/base.gen/sources_1/bd/base/ip/base_m00_regslice_14/base_m00_regslice_14_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_m00_regslice_14'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
