# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/wu/__PYNQ__/board_grey/Pynq-Z2/base/base/base.srcs/sources_1/ip/main_process_0/main_process_0.xci
# IP: The module: 'main_process_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/wu/__PYNQ__/board_grey/Pynq-Z2/base/base/base.gen/sources_1/ip/main_process_0_4/constraints/main_process_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_process_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/wu/__PYNQ__/board_grey/Pynq-Z2/base/base/base.srcs/sources_1/ip/main_process_0/main_process_0.xci
# IP: The module: 'main_process_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/wu/__PYNQ__/board_grey/Pynq-Z2/base/base/base.gen/sources_1/ip/main_process_0_4/constraints/main_process_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_process_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
