#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst_n", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("i_a11", 16, hls_in, 0, "ap_none", "in_data", 1),
	Port_Property("i_a12", 16, hls_in, 1, "ap_none", "in_data", 1),
	Port_Property("i_a13", 16, hls_in, 2, "ap_none", "in_data", 1),
	Port_Property("i_a21", 16, hls_in, 3, "ap_none", "in_data", 1),
	Port_Property("i_a22", 16, hls_in, 4, "ap_none", "in_data", 1),
	Port_Property("i_a23", 16, hls_in, 5, "ap_none", "in_data", 1),
	Port_Property("i_a31", 16, hls_in, 6, "ap_none", "in_data", 1),
	Port_Property("i_a32", 16, hls_in, 7, "ap_none", "in_data", 1),
	Port_Property("i_a33", 16, hls_in, 8, "ap_none", "in_data", 1),
	Port_Property("i_p1", 19, hls_in, 9, "ap_none", "in_data", 1),
	Port_Property("i_p2", 19, hls_in, 10, "ap_none", "in_data", 1),
	Port_Property("i_p3", 19, hls_in, 11, "ap_none", "in_data", 1),
	Port_Property("y_scale", 12, hls_in, 12, "ap_none", "in_data", 1),
	Port_Property("z_scale", 12, hls_in, 13, "ap_none", "in_data", 1),
	Port_Property("data_stream_TDATA", 64, hls_in, 14, "axis", "in_data", 1),
	Port_Property("data_stream_TVALID", 1, hls_in, 17, "axis", "in_vld", 1),
	Port_Property("data_stream_TREADY", 1, hls_out, 17, "axis", "in_acc", 1),
	Port_Property("data_stream_TKEEP", 8, hls_in, 15, "axis", "in_data", 1),
	Port_Property("data_stream_TSTRB", 8, hls_in, 16, "axis", "in_data", 1),
	Port_Property("data_stream_TLAST", 1, hls_in, 17, "axis", "in_data", 1),
	Port_Property("output_stream_TDATA", 24, hls_out, 18, "axis", "out_data", 1),
	Port_Property("output_stream_TVALID", 1, hls_out, 21, "axis", "out_vld", 1),
	Port_Property("output_stream_TREADY", 1, hls_in, 21, "axis", "out_acc", 1),
	Port_Property("output_stream_TKEEP", 3, hls_out, 19, "axis", "out_data", 1),
	Port_Property("output_stream_TSTRB", 3, hls_out, 20, "axis", "out_data", 1),
	Port_Property("output_stream_TLAST", 1, hls_out, 21, "axis", "out_data", 1),
};
const char* HLS_Design_Meta::dut_name = "main_process";
