// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module main_process_zbuffer (
        ap_start,
        ap_ready,
        x_index_0_val,
        y_index_0_val,
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_8_address1,
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_8_ce1,
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_8_we1,
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_8_d1,
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_7_address1,
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_7_ce1,
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_7_we1,
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_7_d1,
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_6_address1,
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_6_ce1,
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_6_we1,
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_6_d1,
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_5_address1,
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_5_ce1,
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_5_we1,
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_5_d1,
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_4_address1,
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_4_ce1,
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_4_we1,
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_4_d1,
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_3_address1,
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_3_ce1,
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_3_we1,
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_3_d1,
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_2_address1,
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_2_ce1,
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_2_we1,
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_2_d1,
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_1_address1,
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_1_ce1,
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_1_we1,
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_1_d1,
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_address1,
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_ce1,
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_we1,
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_d1,
        ap_rst
);


input   ap_start;
output   ap_ready;
input  [6:0] x_index_0_val;
input  [6:0] y_index_0_val;
output  [13:0] zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_8_address1;
output   zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_8_ce1;
output   zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_8_we1;
output  [17:0] zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_8_d1;
output  [13:0] zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_7_address1;
output   zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_7_ce1;
output   zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_7_we1;
output  [17:0] zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_7_d1;
output  [13:0] zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_6_address1;
output   zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_6_ce1;
output   zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_6_we1;
output  [17:0] zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_6_d1;
output  [13:0] zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_5_address1;
output   zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_5_ce1;
output   zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_5_we1;
output  [17:0] zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_5_d1;
output  [13:0] zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_4_address1;
output   zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_4_ce1;
output   zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_4_we1;
output  [17:0] zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_4_d1;
output  [13:0] zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_3_address1;
output   zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_3_ce1;
output   zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_3_we1;
output  [17:0] zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_3_d1;
output  [13:0] zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_2_address1;
output   zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_2_ce1;
output   zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_2_we1;
output  [17:0] zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_2_d1;
output  [13:0] zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_1_address1;
output   zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_1_ce1;
output   zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_1_we1;
output  [17:0] zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_1_d1;
output  [13:0] zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_address1;
output   zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_ce1;
output   zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_we1;
output  [17:0] zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_d1;
input   ap_rst;

wire   [63:0] zext_ln29_fu_228_p1;
reg    zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_8_we1_local;
reg    zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_8_ce1_local;
reg    zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_7_we1_local;
reg    zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_7_ce1_local;
reg    zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_6_we1_local;
reg    zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_6_ce1_local;
reg    zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_5_we1_local;
reg    zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_5_ce1_local;
reg    zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_4_we1_local;
reg    zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_4_ce1_local;
reg    zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_3_we1_local;
reg    zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_3_ce1_local;
reg    zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_2_we1_local;
reg    zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_2_ce1_local;
reg    zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_1_we1_local;
reg    zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_1_ce1_local;
reg    zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_we1_local;
reg    zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_ce1_local;
wire   [13:0] tmp_fu_220_p3;
wire    ap_ce_reg;

always @ (*) begin
    if ((ap_start == 1'b1)) begin
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_1_ce1_local = 1'b1;
    end else begin
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b1)) begin
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_1_we1_local = 1'b1;
    end else begin
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_1_we1_local = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b1)) begin
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_2_ce1_local = 1'b1;
    end else begin
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_2_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b1)) begin
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_2_we1_local = 1'b1;
    end else begin
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_2_we1_local = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b1)) begin
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_3_ce1_local = 1'b1;
    end else begin
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_3_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b1)) begin
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_3_we1_local = 1'b1;
    end else begin
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_3_we1_local = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b1)) begin
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_4_ce1_local = 1'b1;
    end else begin
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_4_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b1)) begin
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_4_we1_local = 1'b1;
    end else begin
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_4_we1_local = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b1)) begin
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_5_ce1_local = 1'b1;
    end else begin
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_5_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b1)) begin
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_5_we1_local = 1'b1;
    end else begin
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_5_we1_local = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b1)) begin
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_6_ce1_local = 1'b1;
    end else begin
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_6_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b1)) begin
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_6_we1_local = 1'b1;
    end else begin
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_6_we1_local = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b1)) begin
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_7_ce1_local = 1'b1;
    end else begin
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_7_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b1)) begin
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_7_we1_local = 1'b1;
    end else begin
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_7_we1_local = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b1)) begin
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_8_ce1_local = 1'b1;
    end else begin
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_8_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b1)) begin
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_8_we1_local = 1'b1;
    end else begin
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_8_we1_local = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b1)) begin
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_ce1_local = 1'b1;
    end else begin
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b1)) begin
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_we1_local = 1'b1;
    end else begin
        zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_we1_local = 1'b0;
    end
end

assign ap_ready = ap_start;

assign tmp_fu_220_p3 = {{x_index_0_val}, {y_index_0_val}};

assign zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_1_address1 = zext_ln29_fu_228_p1;

assign zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_1_ce1 = zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_1_ce1_local;

assign zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_1_d1 = 18'd131072;

assign zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_1_we1 = zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_1_we1_local;

assign zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_2_address1 = zext_ln29_fu_228_p1;

assign zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_2_ce1 = zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_2_ce1_local;

assign zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_2_d1 = 18'd131072;

assign zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_2_we1 = zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_2_we1_local;

assign zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_3_address1 = zext_ln29_fu_228_p1;

assign zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_3_ce1 = zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_3_ce1_local;

assign zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_3_d1 = 18'd131072;

assign zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_3_we1 = zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_3_we1_local;

assign zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_4_address1 = zext_ln29_fu_228_p1;

assign zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_4_ce1 = zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_4_ce1_local;

assign zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_4_d1 = 18'd131072;

assign zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_4_we1 = zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_4_we1_local;

assign zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_5_address1 = zext_ln29_fu_228_p1;

assign zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_5_ce1 = zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_5_ce1_local;

assign zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_5_d1 = 18'd131072;

assign zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_5_we1 = zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_5_we1_local;

assign zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_6_address1 = zext_ln29_fu_228_p1;

assign zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_6_ce1 = zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_6_ce1_local;

assign zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_6_d1 = 18'd131072;

assign zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_6_we1 = zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_6_we1_local;

assign zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_7_address1 = zext_ln29_fu_228_p1;

assign zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_7_ce1 = zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_7_ce1_local;

assign zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_7_d1 = 18'd131072;

assign zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_7_we1 = zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_7_we1_local;

assign zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_8_address1 = zext_ln29_fu_228_p1;

assign zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_8_ce1 = zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_8_ce1_local;

assign zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_8_d1 = 18'd131072;

assign zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_8_we1 = zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_8_we1_local;

assign zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_address1 = zext_ln29_fu_228_p1;

assign zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_ce1 = zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_ce1_local;

assign zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_d1 = 18'd131072;

assign zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_we1 = zbuffer_ap_uint_ap_uint_ap_uint_ap_uint_ap_fixed_bool_z_buffer_we1_local;

assign zext_ln29_fu_228_p1 = tmp_fu_220_p3;

endmodule //main_process_zbuffer
