transcript off
onbreak {quit -force}
onerror {quit -force}
transcript on

vlib work
vlib riviera/xilinx_vip
vlib riviera/xpm
vlib riviera/xlconcat_v2_1_6
vlib riviera/xil_defaultlib
vlib riviera/axi_infrastructure_v1_1_0
vlib riviera/axi_vip_v1_1_17
vlib riviera/processing_system7_vip_v1_0_19
vlib riviera/generic_baseblocks_v2_1_2
vlib riviera/axi_register_slice_v2_1_31
vlib riviera/fifo_generator_v13_2_10
vlib riviera/axi_data_fifo_v2_1_30
vlib riviera/axi_crossbar_v2_1_32
vlib riviera/lib_cdc_v1_0_3
vlib riviera/proc_sys_reset_v5_0_15
vlib riviera/axi_lite_ipif_v3_0_4
vlib riviera/axi_intc_v4_1_19
vlib riviera/lib_pkg_v1_0_4
vlib riviera/lib_fifo_v1_0_19
vlib riviera/blk_mem_gen_v8_4_8
vlib riviera/lib_bmg_v1_0_17
vlib riviera/lib_srl_fifo_v1_0_4
vlib riviera/axi_datamover_v5_1_33
vlib riviera/axi_vdma_v6_3_19
vlib riviera/axis_infrastructure_v1_1_1
vlib riviera/axis_register_slice_v1_1_31
vlib riviera/interrupt_control_v3_1_5
vlib riviera/axi_gpio_v2_0_33
vlib riviera/v_vid_in_axi4s_v5_0_4
vlib riviera/v_tc_v6_2_8
vlib riviera/v_tc_v6_1_14
vlib riviera/v_vid_in_axi4s_v4_0_11
vlib riviera/v_axi4s_vid_out_v4_0_18
vlib riviera/axi_sg_v4_1_18
vlib riviera/axi_dma_v7_1_32
vlib riviera/axis_dwidth_converter_v1_1_30
vlib riviera/axi_protocol_converter_v2_1_31
vlib riviera/axi_clock_converter_v2_1_30
vlib riviera/axi_dwidth_converter_v2_1_31

vmap xilinx_vip riviera/xilinx_vip
vmap xpm riviera/xpm
vmap xlconcat_v2_1_6 riviera/xlconcat_v2_1_6
vmap xil_defaultlib riviera/xil_defaultlib
vmap axi_infrastructure_v1_1_0 riviera/axi_infrastructure_v1_1_0
vmap axi_vip_v1_1_17 riviera/axi_vip_v1_1_17
vmap processing_system7_vip_v1_0_19 riviera/processing_system7_vip_v1_0_19
vmap generic_baseblocks_v2_1_2 riviera/generic_baseblocks_v2_1_2
vmap axi_register_slice_v2_1_31 riviera/axi_register_slice_v2_1_31
vmap fifo_generator_v13_2_10 riviera/fifo_generator_v13_2_10
vmap axi_data_fifo_v2_1_30 riviera/axi_data_fifo_v2_1_30
vmap axi_crossbar_v2_1_32 riviera/axi_crossbar_v2_1_32
vmap lib_cdc_v1_0_3 riviera/lib_cdc_v1_0_3
vmap proc_sys_reset_v5_0_15 riviera/proc_sys_reset_v5_0_15
vmap axi_lite_ipif_v3_0_4 riviera/axi_lite_ipif_v3_0_4
vmap axi_intc_v4_1_19 riviera/axi_intc_v4_1_19
vmap lib_pkg_v1_0_4 riviera/lib_pkg_v1_0_4
vmap lib_fifo_v1_0_19 riviera/lib_fifo_v1_0_19
vmap blk_mem_gen_v8_4_8 riviera/blk_mem_gen_v8_4_8
vmap lib_bmg_v1_0_17 riviera/lib_bmg_v1_0_17
vmap lib_srl_fifo_v1_0_4 riviera/lib_srl_fifo_v1_0_4
vmap axi_datamover_v5_1_33 riviera/axi_datamover_v5_1_33
vmap axi_vdma_v6_3_19 riviera/axi_vdma_v6_3_19
vmap axis_infrastructure_v1_1_1 riviera/axis_infrastructure_v1_1_1
vmap axis_register_slice_v1_1_31 riviera/axis_register_slice_v1_1_31
vmap interrupt_control_v3_1_5 riviera/interrupt_control_v3_1_5
vmap axi_gpio_v2_0_33 riviera/axi_gpio_v2_0_33
vmap v_vid_in_axi4s_v5_0_4 riviera/v_vid_in_axi4s_v5_0_4
vmap v_tc_v6_2_8 riviera/v_tc_v6_2_8
vmap v_tc_v6_1_14 riviera/v_tc_v6_1_14
vmap v_vid_in_axi4s_v4_0_11 riviera/v_vid_in_axi4s_v4_0_11
vmap v_axi4s_vid_out_v4_0_18 riviera/v_axi4s_vid_out_v4_0_18
vmap axi_sg_v4_1_18 riviera/axi_sg_v4_1_18
vmap axi_dma_v7_1_32 riviera/axi_dma_v7_1_32
vmap axis_dwidth_converter_v1_1_30 riviera/axis_dwidth_converter_v1_1_30
vmap axi_protocol_converter_v2_1_31 riviera/axi_protocol_converter_v2_1_31
vmap axi_clock_converter_v2_1_30 riviera/axi_clock_converter_v2_1_30
vmap axi_dwidth_converter_v2_1_31 riviera/axi_dwidth_converter_v2_1_31

vlog -work xilinx_vip  -incr "+incdir+/tools/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xlconcat_v2_1_6 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l processing_system7_vip_v1_0_19 -l generic_baseblocks_v2_1_2 -l axi_register_slice_v2_1_31 -l fifo_generator_v13_2_10 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l axi_lite_ipif_v3_0_4 -l axi_intc_v4_1_19 -l lib_pkg_v1_0_4 -l lib_fifo_v1_0_19 -l blk_mem_gen_v8_4_8 -l lib_bmg_v1_0_17 -l lib_srl_fifo_v1_0_4 -l axi_datamover_v5_1_33 -l axi_vdma_v6_3_19 -l axis_infrastructure_v1_1_1 -l axis_register_slice_v1_1_31 -l interrupt_control_v3_1_5 -l axi_gpio_v2_0_33 -l v_vid_in_axi4s_v5_0_4 -l v_tc_v6_2_8 -l v_tc_v6_1_14 -l v_vid_in_axi4s_v4_0_11 -l v_axi4s_vid_out_v4_0_18 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l axis_dwidth_converter_v1_1_30 -l axi_protocol_converter_v2_1_31 -l axi_clock_converter_v2_1_30 -l axi_dwidth_converter_v2_1_31 \
"/tools/Xilinx/Vivado/2024.1/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
"/tools/Xilinx/Vivado/2024.1/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
"/tools/Xilinx/Vivado/2024.1/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
"/tools/Xilinx/Vivado/2024.1/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
"/tools/Xilinx/Vivado/2024.1/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
"/tools/Xilinx/Vivado/2024.1/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
"/tools/Xilinx/Vivado/2024.1/data/xilinx_vip/hdl/axi_vip_if.sv" \
"/tools/Xilinx/Vivado/2024.1/data/xilinx_vip/hdl/clk_vip_if.sv" \
"/tools/Xilinx/Vivado/2024.1/data/xilinx_vip/hdl/rst_vip_if.sv" \

vlog -work xpm  -incr "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/b28c/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/a4a8/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/3c6d/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/7611/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/1376/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" "+incdir+/tools/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xlconcat_v2_1_6 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l processing_system7_vip_v1_0_19 -l generic_baseblocks_v2_1_2 -l axi_register_slice_v2_1_31 -l fifo_generator_v13_2_10 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l axi_lite_ipif_v3_0_4 -l axi_intc_v4_1_19 -l lib_pkg_v1_0_4 -l lib_fifo_v1_0_19 -l blk_mem_gen_v8_4_8 -l lib_bmg_v1_0_17 -l lib_srl_fifo_v1_0_4 -l axi_datamover_v5_1_33 -l axi_vdma_v6_3_19 -l axis_infrastructure_v1_1_1 -l axis_register_slice_v1_1_31 -l interrupt_control_v3_1_5 -l axi_gpio_v2_0_33 -l v_vid_in_axi4s_v5_0_4 -l v_tc_v6_2_8 -l v_tc_v6_1_14 -l v_vid_in_axi4s_v4_0_11 -l v_axi4s_vid_out_v4_0_18 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l axis_dwidth_converter_v1_1_30 -l axi_protocol_converter_v2_1_31 -l axi_clock_converter_v2_1_30 -l axi_dwidth_converter_v2_1_31 \
"/tools/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
"/tools/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
"/tools/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \

vcom -work xpm -93  -incr \
"/tools/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_VCOMP.vhd" \

vlog -work xlconcat_v2_1_6  -incr -v2k5 "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/b28c/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/a4a8/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/3c6d/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/7611/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/1376/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" "+incdir+/tools/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xlconcat_v2_1_6 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l processing_system7_vip_v1_0_19 -l generic_baseblocks_v2_1_2 -l axi_register_slice_v2_1_31 -l fifo_generator_v13_2_10 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l axi_lite_ipif_v3_0_4 -l axi_intc_v4_1_19 -l lib_pkg_v1_0_4 -l lib_fifo_v1_0_19 -l blk_mem_gen_v8_4_8 -l lib_bmg_v1_0_17 -l lib_srl_fifo_v1_0_4 -l axi_datamover_v5_1_33 -l axi_vdma_v6_3_19 -l axis_infrastructure_v1_1_1 -l axis_register_slice_v1_1_31 -l interrupt_control_v3_1_5 -l axi_gpio_v2_0_33 -l v_vid_in_axi4s_v5_0_4 -l v_tc_v6_2_8 -l v_tc_v6_1_14 -l v_vid_in_axi4s_v4_0_11 -l v_axi4s_vid_out_v4_0_18 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l axis_dwidth_converter_v1_1_30 -l axi_protocol_converter_v2_1_31 -l axi_clock_converter_v2_1_30 -l axi_dwidth_converter_v2_1_31 \
"../../../../base.gen/sources_1/bd/base/ipshared/6120/hdl/xlconcat_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/b28c/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/a4a8/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/3c6d/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/7611/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/1376/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" "+incdir+/tools/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xlconcat_v2_1_6 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l processing_system7_vip_v1_0_19 -l generic_baseblocks_v2_1_2 -l axi_register_slice_v2_1_31 -l fifo_generator_v13_2_10 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l axi_lite_ipif_v3_0_4 -l axi_intc_v4_1_19 -l lib_pkg_v1_0_4 -l lib_fifo_v1_0_19 -l blk_mem_gen_v8_4_8 -l lib_bmg_v1_0_17 -l lib_srl_fifo_v1_0_4 -l axi_datamover_v5_1_33 -l axi_vdma_v6_3_19 -l axis_infrastructure_v1_1_1 -l axis_register_slice_v1_1_31 -l interrupt_control_v3_1_5 -l axi_gpio_v2_0_33 -l v_vid_in_axi4s_v5_0_4 -l v_tc_v6_2_8 -l v_tc_v6_1_14 -l v_vid_in_axi4s_v4_0_11 -l v_axi4s_vid_out_v4_0_18 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l axis_dwidth_converter_v1_1_30 -l axi_protocol_converter_v2_1_31 -l axi_clock_converter_v2_1_30 -l axi_dwidth_converter_v2_1_31 \
"../../../../base.gen/sources_1/bd/base/ip/base_concat_interrupts_0/sim/base_concat_interrupts_0.v" \

vlog -work axi_infrastructure_v1_1_0  -incr -v2k5 "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/b28c/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/a4a8/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/3c6d/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/7611/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/1376/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" "+incdir+/tools/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xlconcat_v2_1_6 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l processing_system7_vip_v1_0_19 -l generic_baseblocks_v2_1_2 -l axi_register_slice_v2_1_31 -l fifo_generator_v13_2_10 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l axi_lite_ipif_v3_0_4 -l axi_intc_v4_1_19 -l lib_pkg_v1_0_4 -l lib_fifo_v1_0_19 -l blk_mem_gen_v8_4_8 -l lib_bmg_v1_0_17 -l lib_srl_fifo_v1_0_4 -l axi_datamover_v5_1_33 -l axi_vdma_v6_3_19 -l axis_infrastructure_v1_1_1 -l axis_register_slice_v1_1_31 -l interrupt_control_v3_1_5 -l axi_gpio_v2_0_33 -l v_vid_in_axi4s_v5_0_4 -l v_tc_v6_2_8 -l v_tc_v6_1_14 -l v_vid_in_axi4s_v4_0_11 -l v_axi4s_vid_out_v4_0_18 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l axis_dwidth_converter_v1_1_30 -l axi_protocol_converter_v2_1_31 -l axi_clock_converter_v2_1_30 -l axi_dwidth_converter_v2_1_31 \
"../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \

vlog -work axi_vip_v1_1_17  -incr "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/b28c/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/a4a8/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/3c6d/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/7611/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/1376/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" "+incdir+/tools/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xlconcat_v2_1_6 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l processing_system7_vip_v1_0_19 -l generic_baseblocks_v2_1_2 -l axi_register_slice_v2_1_31 -l fifo_generator_v13_2_10 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l axi_lite_ipif_v3_0_4 -l axi_intc_v4_1_19 -l lib_pkg_v1_0_4 -l lib_fifo_v1_0_19 -l blk_mem_gen_v8_4_8 -l lib_bmg_v1_0_17 -l lib_srl_fifo_v1_0_4 -l axi_datamover_v5_1_33 -l axi_vdma_v6_3_19 -l axis_infrastructure_v1_1_1 -l axis_register_slice_v1_1_31 -l interrupt_control_v3_1_5 -l axi_gpio_v2_0_33 -l v_vid_in_axi4s_v5_0_4 -l v_tc_v6_2_8 -l v_tc_v6_1_14 -l v_vid_in_axi4s_v4_0_11 -l v_axi4s_vid_out_v4_0_18 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l axis_dwidth_converter_v1_1_30 -l axi_protocol_converter_v2_1_31 -l axi_clock_converter_v2_1_30 -l axi_dwidth_converter_v2_1_31 \
"../../../../base.gen/sources_1/bd/base/ipshared/4d04/hdl/axi_vip_v1_1_vl_rfs.sv" \

vlog -work processing_system7_vip_v1_0_19  -incr "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/b28c/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/a4a8/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/3c6d/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/7611/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/1376/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" "+incdir+/tools/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xlconcat_v2_1_6 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l processing_system7_vip_v1_0_19 -l generic_baseblocks_v2_1_2 -l axi_register_slice_v2_1_31 -l fifo_generator_v13_2_10 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l axi_lite_ipif_v3_0_4 -l axi_intc_v4_1_19 -l lib_pkg_v1_0_4 -l lib_fifo_v1_0_19 -l blk_mem_gen_v8_4_8 -l lib_bmg_v1_0_17 -l lib_srl_fifo_v1_0_4 -l axi_datamover_v5_1_33 -l axi_vdma_v6_3_19 -l axis_infrastructure_v1_1_1 -l axis_register_slice_v1_1_31 -l interrupt_control_v3_1_5 -l axi_gpio_v2_0_33 -l v_vid_in_axi4s_v5_0_4 -l v_tc_v6_2_8 -l v_tc_v6_1_14 -l v_vid_in_axi4s_v4_0_11 -l v_axi4s_vid_out_v4_0_18 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l axis_dwidth_converter_v1_1_30 -l axi_protocol_converter_v2_1_31 -l axi_clock_converter_v2_1_30 -l axi_dwidth_converter_v2_1_31 \
"../../../../base.gen/sources_1/bd/base/ipshared/b28c/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/b28c/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/a4a8/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/3c6d/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/7611/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/1376/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" "+incdir+/tools/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xlconcat_v2_1_6 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l processing_system7_vip_v1_0_19 -l generic_baseblocks_v2_1_2 -l axi_register_slice_v2_1_31 -l fifo_generator_v13_2_10 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l axi_lite_ipif_v3_0_4 -l axi_intc_v4_1_19 -l lib_pkg_v1_0_4 -l lib_fifo_v1_0_19 -l blk_mem_gen_v8_4_8 -l lib_bmg_v1_0_17 -l lib_srl_fifo_v1_0_4 -l axi_datamover_v5_1_33 -l axi_vdma_v6_3_19 -l axis_infrastructure_v1_1_1 -l axis_register_slice_v1_1_31 -l interrupt_control_v3_1_5 -l axi_gpio_v2_0_33 -l v_vid_in_axi4s_v5_0_4 -l v_tc_v6_2_8 -l v_tc_v6_1_14 -l v_vid_in_axi4s_v4_0_11 -l v_axi4s_vid_out_v4_0_18 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l axis_dwidth_converter_v1_1_30 -l axi_protocol_converter_v2_1_31 -l axi_clock_converter_v2_1_30 -l axi_dwidth_converter_v2_1_31 \
"../../../../base.gen/sources_1/bd/base/ip/base_ps7_0_0/sim/base_ps7_0_0.v" \

vlog -work generic_baseblocks_v2_1_2  -incr -v2k5 "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/b28c/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/a4a8/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/3c6d/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/7611/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/1376/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" "+incdir+/tools/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xlconcat_v2_1_6 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l processing_system7_vip_v1_0_19 -l generic_baseblocks_v2_1_2 -l axi_register_slice_v2_1_31 -l fifo_generator_v13_2_10 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l axi_lite_ipif_v3_0_4 -l axi_intc_v4_1_19 -l lib_pkg_v1_0_4 -l lib_fifo_v1_0_19 -l blk_mem_gen_v8_4_8 -l lib_bmg_v1_0_17 -l lib_srl_fifo_v1_0_4 -l axi_datamover_v5_1_33 -l axi_vdma_v6_3_19 -l axis_infrastructure_v1_1_1 -l axis_register_slice_v1_1_31 -l interrupt_control_v3_1_5 -l axi_gpio_v2_0_33 -l v_vid_in_axi4s_v5_0_4 -l v_tc_v6_2_8 -l v_tc_v6_1_14 -l v_vid_in_axi4s_v4_0_11 -l v_axi4s_vid_out_v4_0_18 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l axis_dwidth_converter_v1_1_30 -l axi_protocol_converter_v2_1_31 -l axi_clock_converter_v2_1_30 -l axi_dwidth_converter_v2_1_31 \
"../../../../base.gen/sources_1/bd/base/ipshared/0c28/hdl/generic_baseblocks_v2_1_vl_rfs.v" \

vlog -work axi_register_slice_v2_1_31  -incr -v2k5 "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/b28c/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/a4a8/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/3c6d/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/7611/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/1376/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" "+incdir+/tools/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xlconcat_v2_1_6 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l processing_system7_vip_v1_0_19 -l generic_baseblocks_v2_1_2 -l axi_register_slice_v2_1_31 -l fifo_generator_v13_2_10 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l axi_lite_ipif_v3_0_4 -l axi_intc_v4_1_19 -l lib_pkg_v1_0_4 -l lib_fifo_v1_0_19 -l blk_mem_gen_v8_4_8 -l lib_bmg_v1_0_17 -l lib_srl_fifo_v1_0_4 -l axi_datamover_v5_1_33 -l axi_vdma_v6_3_19 -l axis_infrastructure_v1_1_1 -l axis_register_slice_v1_1_31 -l interrupt_control_v3_1_5 -l axi_gpio_v2_0_33 -l v_vid_in_axi4s_v5_0_4 -l v_tc_v6_2_8 -l v_tc_v6_1_14 -l v_vid_in_axi4s_v4_0_11 -l v_axi4s_vid_out_v4_0_18 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l axis_dwidth_converter_v1_1_30 -l axi_protocol_converter_v2_1_31 -l axi_clock_converter_v2_1_30 -l axi_dwidth_converter_v2_1_31 \
"../../../../base.gen/sources_1/bd/base/ipshared/92b2/hdl/axi_register_slice_v2_1_vl_rfs.v" \

vlog -work fifo_generator_v13_2_10  -incr -v2k5 "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/b28c/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/a4a8/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/3c6d/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/7611/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/1376/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" "+incdir+/tools/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xlconcat_v2_1_6 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l processing_system7_vip_v1_0_19 -l generic_baseblocks_v2_1_2 -l axi_register_slice_v2_1_31 -l fifo_generator_v13_2_10 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l axi_lite_ipif_v3_0_4 -l axi_intc_v4_1_19 -l lib_pkg_v1_0_4 -l lib_fifo_v1_0_19 -l blk_mem_gen_v8_4_8 -l lib_bmg_v1_0_17 -l lib_srl_fifo_v1_0_4 -l axi_datamover_v5_1_33 -l axi_vdma_v6_3_19 -l axis_infrastructure_v1_1_1 -l axis_register_slice_v1_1_31 -l interrupt_control_v3_1_5 -l axi_gpio_v2_0_33 -l v_vid_in_axi4s_v5_0_4 -l v_tc_v6_2_8 -l v_tc_v6_1_14 -l v_vid_in_axi4s_v4_0_11 -l v_axi4s_vid_out_v4_0_18 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l axis_dwidth_converter_v1_1_30 -l axi_protocol_converter_v2_1_31 -l axi_clock_converter_v2_1_30 -l axi_dwidth_converter_v2_1_31 \
"../../../../base.gen/sources_1/bd/base/ipshared/1443/simulation/fifo_generator_vlog_beh.v" \

vcom -work fifo_generator_v13_2_10 -93  -incr \
"../../../../base.gen/sources_1/bd/base/ipshared/1443/hdl/fifo_generator_v13_2_rfs.vhd" \

vlog -work fifo_generator_v13_2_10  -incr -v2k5 "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/b28c/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/a4a8/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/3c6d/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/7611/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/1376/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" "+incdir+/tools/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xlconcat_v2_1_6 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l processing_system7_vip_v1_0_19 -l generic_baseblocks_v2_1_2 -l axi_register_slice_v2_1_31 -l fifo_generator_v13_2_10 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l axi_lite_ipif_v3_0_4 -l axi_intc_v4_1_19 -l lib_pkg_v1_0_4 -l lib_fifo_v1_0_19 -l blk_mem_gen_v8_4_8 -l lib_bmg_v1_0_17 -l lib_srl_fifo_v1_0_4 -l axi_datamover_v5_1_33 -l axi_vdma_v6_3_19 -l axis_infrastructure_v1_1_1 -l axis_register_slice_v1_1_31 -l interrupt_control_v3_1_5 -l axi_gpio_v2_0_33 -l v_vid_in_axi4s_v5_0_4 -l v_tc_v6_2_8 -l v_tc_v6_1_14 -l v_vid_in_axi4s_v4_0_11 -l v_axi4s_vid_out_v4_0_18 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l axis_dwidth_converter_v1_1_30 -l axi_protocol_converter_v2_1_31 -l axi_clock_converter_v2_1_30 -l axi_dwidth_converter_v2_1_31 \
"../../../../base.gen/sources_1/bd/base/ipshared/1443/hdl/fifo_generator_v13_2_rfs.v" \

vlog -work axi_data_fifo_v2_1_30  -incr -v2k5 "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/b28c/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/a4a8/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/3c6d/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/7611/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/1376/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" "+incdir+/tools/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xlconcat_v2_1_6 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l processing_system7_vip_v1_0_19 -l generic_baseblocks_v2_1_2 -l axi_register_slice_v2_1_31 -l fifo_generator_v13_2_10 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l axi_lite_ipif_v3_0_4 -l axi_intc_v4_1_19 -l lib_pkg_v1_0_4 -l lib_fifo_v1_0_19 -l blk_mem_gen_v8_4_8 -l lib_bmg_v1_0_17 -l lib_srl_fifo_v1_0_4 -l axi_datamover_v5_1_33 -l axi_vdma_v6_3_19 -l axis_infrastructure_v1_1_1 -l axis_register_slice_v1_1_31 -l interrupt_control_v3_1_5 -l axi_gpio_v2_0_33 -l v_vid_in_axi4s_v5_0_4 -l v_tc_v6_2_8 -l v_tc_v6_1_14 -l v_vid_in_axi4s_v4_0_11 -l v_axi4s_vid_out_v4_0_18 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l axis_dwidth_converter_v1_1_30 -l axi_protocol_converter_v2_1_31 -l axi_clock_converter_v2_1_30 -l axi_dwidth_converter_v2_1_31 \
"../../../../base.gen/sources_1/bd/base/ipshared/9692/hdl/axi_data_fifo_v2_1_vl_rfs.v" \

vlog -work axi_crossbar_v2_1_32  -incr -v2k5 "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/b28c/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/a4a8/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/3c6d/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/7611/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/1376/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" "+incdir+/tools/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xlconcat_v2_1_6 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l processing_system7_vip_v1_0_19 -l generic_baseblocks_v2_1_2 -l axi_register_slice_v2_1_31 -l fifo_generator_v13_2_10 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l axi_lite_ipif_v3_0_4 -l axi_intc_v4_1_19 -l lib_pkg_v1_0_4 -l lib_fifo_v1_0_19 -l blk_mem_gen_v8_4_8 -l lib_bmg_v1_0_17 -l lib_srl_fifo_v1_0_4 -l axi_datamover_v5_1_33 -l axi_vdma_v6_3_19 -l axis_infrastructure_v1_1_1 -l axis_register_slice_v1_1_31 -l interrupt_control_v3_1_5 -l axi_gpio_v2_0_33 -l v_vid_in_axi4s_v5_0_4 -l v_tc_v6_2_8 -l v_tc_v6_1_14 -l v_vid_in_axi4s_v4_0_11 -l v_axi4s_vid_out_v4_0_18 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l axis_dwidth_converter_v1_1_30 -l axi_protocol_converter_v2_1_31 -l axi_clock_converter_v2_1_30 -l axi_dwidth_converter_v2_1_31 \
"../../../../base.gen/sources_1/bd/base/ipshared/e9d8/hdl/axi_crossbar_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/b28c/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/a4a8/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/3c6d/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/7611/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/1376/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" "+incdir+/tools/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xlconcat_v2_1_6 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l processing_system7_vip_v1_0_19 -l generic_baseblocks_v2_1_2 -l axi_register_slice_v2_1_31 -l fifo_generator_v13_2_10 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l axi_lite_ipif_v3_0_4 -l axi_intc_v4_1_19 -l lib_pkg_v1_0_4 -l lib_fifo_v1_0_19 -l blk_mem_gen_v8_4_8 -l lib_bmg_v1_0_17 -l lib_srl_fifo_v1_0_4 -l axi_datamover_v5_1_33 -l axi_vdma_v6_3_19 -l axis_infrastructure_v1_1_1 -l axis_register_slice_v1_1_31 -l interrupt_control_v3_1_5 -l axi_gpio_v2_0_33 -l v_vid_in_axi4s_v5_0_4 -l v_tc_v6_2_8 -l v_tc_v6_1_14 -l v_vid_in_axi4s_v4_0_11 -l v_axi4s_vid_out_v4_0_18 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l axis_dwidth_converter_v1_1_30 -l axi_protocol_converter_v2_1_31 -l axi_clock_converter_v2_1_30 -l axi_dwidth_converter_v2_1_31 \
"../../../../base.gen/sources_1/bd/base/ip/base_xbar_6/sim/base_xbar_6.v" \

vcom -work lib_cdc_v1_0_3 -93  -incr \
"../../../../base.gen/sources_1/bd/base/ipshared/2a4f/hdl/lib_cdc_v1_0_rfs.vhd" \

vcom -work proc_sys_reset_v5_0_15 -93  -incr \
"../../../../base.gen/sources_1/bd/base/ipshared/3a26/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -93  -incr \
"../../../../base.gen/sources_1/bd/base/ip/base_rst_ps7_0_fclk0_0/sim/base_rst_ps7_0_fclk0_0.vhd" \
"../../../../base.gen/sources_1/bd/base/ip/base_rst_ps7_0_fclk1_0/sim/base_rst_ps7_0_fclk1_0.vhd" \

vcom -work axi_lite_ipif_v3_0_4 -93  -incr \
"../../../../base.gen/sources_1/bd/base/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \

vcom -work axi_intc_v4_1_19 -93  -incr \
"../../../../base.gen/sources_1/bd/base/ipshared/558f/hdl/axi_intc_v4_1_vh_rfs.vhd" \

vcom -work xil_defaultlib -93  -incr \
"../../../../base.gen/sources_1/bd/base/ip/base_system_interrupts_0/sim/base_system_interrupts_0.vhd" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/b28c/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/a4a8/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/3c6d/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/7611/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/1376/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" "+incdir+/tools/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xlconcat_v2_1_6 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l processing_system7_vip_v1_0_19 -l generic_baseblocks_v2_1_2 -l axi_register_slice_v2_1_31 -l fifo_generator_v13_2_10 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l axi_lite_ipif_v3_0_4 -l axi_intc_v4_1_19 -l lib_pkg_v1_0_4 -l lib_fifo_v1_0_19 -l blk_mem_gen_v8_4_8 -l lib_bmg_v1_0_17 -l lib_srl_fifo_v1_0_4 -l axi_datamover_v5_1_33 -l axi_vdma_v6_3_19 -l axis_infrastructure_v1_1_1 -l axis_register_slice_v1_1_31 -l interrupt_control_v3_1_5 -l axi_gpio_v2_0_33 -l v_vid_in_axi4s_v5_0_4 -l v_tc_v6_2_8 -l v_tc_v6_1_14 -l v_vid_in_axi4s_v4_0_11 -l v_axi4s_vid_out_v4_0_18 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l axis_dwidth_converter_v1_1_30 -l axi_protocol_converter_v2_1_31 -l axi_clock_converter_v2_1_30 -l axi_dwidth_converter_v2_1_31 \
"../../../../base.gen/sources_1/bd/base/ip/base_xbar_9/sim/base_xbar_9.v" \
"../../../../base.gen/sources_1/bd/base/ip/base_xbar_10/sim/base_xbar_10.v" \

vcom -work lib_pkg_v1_0_4 -93  -incr \
"../../../../base.gen/sources_1/bd/base/ipshared/8c68/hdl/lib_pkg_v1_0_rfs.vhd" \

vcom -work lib_fifo_v1_0_19 -93  -incr \
"../../../../base.gen/sources_1/bd/base/ipshared/0a12/hdl/lib_fifo_v1_0_rfs.vhd" \

vlog -work blk_mem_gen_v8_4_8  -incr -v2k5 "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/b28c/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/a4a8/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/3c6d/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/7611/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/1376/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" "+incdir+/tools/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xlconcat_v2_1_6 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l processing_system7_vip_v1_0_19 -l generic_baseblocks_v2_1_2 -l axi_register_slice_v2_1_31 -l fifo_generator_v13_2_10 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l axi_lite_ipif_v3_0_4 -l axi_intc_v4_1_19 -l lib_pkg_v1_0_4 -l lib_fifo_v1_0_19 -l blk_mem_gen_v8_4_8 -l lib_bmg_v1_0_17 -l lib_srl_fifo_v1_0_4 -l axi_datamover_v5_1_33 -l axi_vdma_v6_3_19 -l axis_infrastructure_v1_1_1 -l axis_register_slice_v1_1_31 -l interrupt_control_v3_1_5 -l axi_gpio_v2_0_33 -l v_vid_in_axi4s_v5_0_4 -l v_tc_v6_2_8 -l v_tc_v6_1_14 -l v_vid_in_axi4s_v4_0_11 -l v_axi4s_vid_out_v4_0_18 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l axis_dwidth_converter_v1_1_30 -l axi_protocol_converter_v2_1_31 -l axi_clock_converter_v2_1_30 -l axi_dwidth_converter_v2_1_31 \
"../../../../base.gen/sources_1/bd/base/ipshared/09bd/simulation/blk_mem_gen_v8_4.v" \

vcom -work lib_bmg_v1_0_17 -93  -incr \
"../../../../base.gen/sources_1/bd/base/ipshared/3f29/hdl/lib_bmg_v1_0_rfs.vhd" \

vcom -work lib_srl_fifo_v1_0_4 -93  -incr \
"../../../../base.gen/sources_1/bd/base/ipshared/1e5a/hdl/lib_srl_fifo_v1_0_rfs.vhd" \

vcom -work axi_datamover_v5_1_33 -93  -incr \
"../../../../base.gen/sources_1/bd/base/ipshared/bf20/hdl/axi_datamover_v5_1_vh_rfs.vhd" \

vlog -work axi_vdma_v6_3_19  -incr -v2k5 "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/b28c/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/a4a8/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/3c6d/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/7611/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/1376/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" "+incdir+/tools/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xlconcat_v2_1_6 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l processing_system7_vip_v1_0_19 -l generic_baseblocks_v2_1_2 -l axi_register_slice_v2_1_31 -l fifo_generator_v13_2_10 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l axi_lite_ipif_v3_0_4 -l axi_intc_v4_1_19 -l lib_pkg_v1_0_4 -l lib_fifo_v1_0_19 -l blk_mem_gen_v8_4_8 -l lib_bmg_v1_0_17 -l lib_srl_fifo_v1_0_4 -l axi_datamover_v5_1_33 -l axi_vdma_v6_3_19 -l axis_infrastructure_v1_1_1 -l axis_register_slice_v1_1_31 -l interrupt_control_v3_1_5 -l axi_gpio_v2_0_33 -l v_vid_in_axi4s_v5_0_4 -l v_tc_v6_2_8 -l v_tc_v6_1_14 -l v_vid_in_axi4s_v4_0_11 -l v_axi4s_vid_out_v4_0_18 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l axis_dwidth_converter_v1_1_30 -l axi_protocol_converter_v2_1_31 -l axi_clock_converter_v2_1_30 -l axi_dwidth_converter_v2_1_31 \
"../../../../base.gen/sources_1/bd/base/ipshared/a4a8/hdl/axi_vdma_v6_3_rfs.v" \

vcom -work axi_vdma_v6_3_19 -93  -incr \
"../../../../base.gen/sources_1/bd/base/ipshared/a4a8/hdl/axi_vdma_v6_3_rfs.vhd" \

vcom -work xil_defaultlib -93  -incr \
"../../../../base.gen/sources_1/bd/base/ip/base_axi_vdma_0/sim/base_axi_vdma_0.vhd" \

vlog -work axis_infrastructure_v1_1_1  -incr -v2k5 "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/b28c/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/a4a8/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/3c6d/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/7611/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/1376/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" "+incdir+/tools/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xlconcat_v2_1_6 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l processing_system7_vip_v1_0_19 -l generic_baseblocks_v2_1_2 -l axi_register_slice_v2_1_31 -l fifo_generator_v13_2_10 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l axi_lite_ipif_v3_0_4 -l axi_intc_v4_1_19 -l lib_pkg_v1_0_4 -l lib_fifo_v1_0_19 -l blk_mem_gen_v8_4_8 -l lib_bmg_v1_0_17 -l lib_srl_fifo_v1_0_4 -l axi_datamover_v5_1_33 -l axi_vdma_v6_3_19 -l axis_infrastructure_v1_1_1 -l axis_register_slice_v1_1_31 -l interrupt_control_v3_1_5 -l axi_gpio_v2_0_33 -l v_vid_in_axi4s_v5_0_4 -l v_tc_v6_2_8 -l v_tc_v6_1_14 -l v_vid_in_axi4s_v4_0_11 -l v_axi4s_vid_out_v4_0_18 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l axis_dwidth_converter_v1_1_30 -l axi_protocol_converter_v2_1_31 -l axi_clock_converter_v2_1_30 -l axi_dwidth_converter_v2_1_31 \
"../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl/axis_infrastructure_v1_1_vl_rfs.v" \

vlog -work axis_register_slice_v1_1_31  -incr -v2k5 "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/b28c/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/a4a8/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/3c6d/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/7611/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/1376/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" "+incdir+/tools/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xlconcat_v2_1_6 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l processing_system7_vip_v1_0_19 -l generic_baseblocks_v2_1_2 -l axi_register_slice_v2_1_31 -l fifo_generator_v13_2_10 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l axi_lite_ipif_v3_0_4 -l axi_intc_v4_1_19 -l lib_pkg_v1_0_4 -l lib_fifo_v1_0_19 -l blk_mem_gen_v8_4_8 -l lib_bmg_v1_0_17 -l lib_srl_fifo_v1_0_4 -l axi_datamover_v5_1_33 -l axi_vdma_v6_3_19 -l axis_infrastructure_v1_1_1 -l axis_register_slice_v1_1_31 -l interrupt_control_v3_1_5 -l axi_gpio_v2_0_33 -l v_vid_in_axi4s_v5_0_4 -l v_tc_v6_2_8 -l v_tc_v6_1_14 -l v_vid_in_axi4s_v4_0_11 -l v_axi4s_vid_out_v4_0_18 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l axis_dwidth_converter_v1_1_30 -l axi_protocol_converter_v2_1_31 -l axi_clock_converter_v2_1_30 -l axi_dwidth_converter_v2_1_31 \
"../../../../base.gen/sources_1/bd/base/ipshared/ca8d/hdl/axis_register_slice_v1_1_vl_rfs.v" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/b28c/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/a4a8/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/3c6d/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/7611/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/1376/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" "+incdir+/tools/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xlconcat_v2_1_6 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l processing_system7_vip_v1_0_19 -l generic_baseblocks_v2_1_2 -l axi_register_slice_v2_1_31 -l fifo_generator_v13_2_10 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l axi_lite_ipif_v3_0_4 -l axi_intc_v4_1_19 -l lib_pkg_v1_0_4 -l lib_fifo_v1_0_19 -l blk_mem_gen_v8_4_8 -l lib_bmg_v1_0_17 -l lib_srl_fifo_v1_0_4 -l axi_datamover_v5_1_33 -l axi_vdma_v6_3_19 -l axis_infrastructure_v1_1_1 -l axis_register_slice_v1_1_31 -l interrupt_control_v3_1_5 -l axi_gpio_v2_0_33 -l v_vid_in_axi4s_v5_0_4 -l v_tc_v6_2_8 -l v_tc_v6_1_14 -l v_vid_in_axi4s_v4_0_11 -l v_axi4s_vid_out_v4_0_18 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l axis_dwidth_converter_v1_1_30 -l axi_protocol_converter_v2_1_31 -l axi_clock_converter_v2_1_30 -l axi_dwidth_converter_v2_1_31 \
"../../../../base.gen/sources_1/bd/base/ip/base_axis_register_slice_0_0/sim/base_axis_register_slice_0_0.v" \
"../../../../base.gen/sources_1/bd/base/ipshared/3c6d/hdl/verilog/color_convert_control_s_axi.v" \
"../../../../base.gen/sources_1/bd/base/ipshared/3c6d/hdl/verilog/color_convert_hls_deadlock_idx0_monitor.v" \
"../../../../base.gen/sources_1/bd/base/ipshared/3c6d/hdl/verilog/color_convert_mac_muladd_10s_8ns_18s_19_4_1.v" \
"../../../../base.gen/sources_1/bd/base/ipshared/3c6d/hdl/verilog/color_convert_mac_muladd_10s_8ns_19s_20_4_1.v" \
"../../../../base.gen/sources_1/bd/base/ipshared/3c6d/hdl/verilog/color_convert_mul_10s_8ns_18_1_1.v" \
"../../../../base.gen/sources_1/bd/base/ipshared/3c6d/hdl/verilog/color_convert_regslice_both.v" \
"../../../../base.gen/sources_1/bd/base/ipshared/3c6d/hdl/verilog/color_convert.v" \
"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/sim/base_color_convert_0.v" \

vcom -work interrupt_control_v3_1_5 -93  -incr \
"../../../../base.gen/sources_1/bd/base/ipshared/d8cc/hdl/interrupt_control_v3_1_vh_rfs.vhd" \

vcom -work axi_gpio_v2_0_33 -93  -incr \
"../../../../base.gen/sources_1/bd/base/ipshared/4208/hdl/axi_gpio_v2_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -93  -incr \
"../../../../base.gen/sources_1/bd/base/ip/base_axi_gpio_hdmiin_0/sim/base_axi_gpio_hdmiin_0.vhd" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/b28c/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/a4a8/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/3c6d/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/7611/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/1376/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" "+incdir+/tools/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xlconcat_v2_1_6 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l processing_system7_vip_v1_0_19 -l generic_baseblocks_v2_1_2 -l axi_register_slice_v2_1_31 -l fifo_generator_v13_2_10 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l axi_lite_ipif_v3_0_4 -l axi_intc_v4_1_19 -l lib_pkg_v1_0_4 -l lib_fifo_v1_0_19 -l blk_mem_gen_v8_4_8 -l lib_bmg_v1_0_17 -l lib_srl_fifo_v1_0_4 -l axi_datamover_v5_1_33 -l axi_vdma_v6_3_19 -l axis_infrastructure_v1_1_1 -l axis_register_slice_v1_1_31 -l interrupt_control_v3_1_5 -l axi_gpio_v2_0_33 -l v_vid_in_axi4s_v5_0_4 -l v_tc_v6_2_8 -l v_tc_v6_1_14 -l v_vid_in_axi4s_v4_0_11 -l v_axi4s_vid_out_v4_0_18 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l axis_dwidth_converter_v1_1_30 -l axi_protocol_converter_v2_1_31 -l axi_clock_converter_v2_1_30 -l axi_dwidth_converter_v2_1_31 \
"../../../../base.gen/sources_1/bd/base/ipshared/4b6f/color_swap.v" \
"../../../../base.gen/sources_1/bd/base/ip/base_color_swap_0_0/sim/base_color_swap_0_0.v" \

vcom -work xil_defaultlib -93  -incr \
"../../../../base.gen/sources_1/bd/base/ipshared/269e/src/SyncBase.vhd" \
"../../../../base.gen/sources_1/bd/base/ipshared/269e/src/EEPROM_8b.vhd" \
"../../../../base.gen/sources_1/bd/base/ipshared/269e/src/TWI_SlaveCtl.vhd" \
"../../../../base.gen/sources_1/bd/base/ipshared/269e/src/GlitchFilter.vhd" \
"../../../../base.gen/sources_1/bd/base/ipshared/269e/src/SyncAsync.vhd" \
"../../../../base.gen/sources_1/bd/base/ipshared/269e/src/DVI_Constants.vhd" \
"../../../../base.gen/sources_1/bd/base/ipshared/269e/src/SyncAsyncReset.vhd" \
"../../../../base.gen/sources_1/bd/base/ipshared/269e/src/PhaseAlign.vhd" \
"../../../../base.gen/sources_1/bd/base/ipshared/269e/src/InputSERDES.vhd" \
"../../../../base.gen/sources_1/bd/base/ipshared/269e/src/ChannelBond.vhd" \
"../../../../base.gen/sources_1/bd/base/ipshared/269e/src/ResyncToBUFG.vhd" \
"../../../../base.gen/sources_1/bd/base/ipshared/269e/src/TMDS_Decoder.vhd" \
"../../../../base.gen/sources_1/bd/base/ipshared/269e/src/TMDS_Clocking.vhd" \
"../../../../base.gen/sources_1/bd/base/ipshared/269e/src/dvi2rgb.vhd" \
"../../../../base.gen/sources_1/bd/base/ip/base_dvi2rgb_0_0/sim/base_dvi2rgb_0_0.vhd" \

vlog -work v_vid_in_axi4s_v5_0_4  -incr -v2k5 "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/b28c/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/a4a8/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/3c6d/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/7611/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/1376/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" "+incdir+/tools/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xlconcat_v2_1_6 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l processing_system7_vip_v1_0_19 -l generic_baseblocks_v2_1_2 -l axi_register_slice_v2_1_31 -l fifo_generator_v13_2_10 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l axi_lite_ipif_v3_0_4 -l axi_intc_v4_1_19 -l lib_pkg_v1_0_4 -l lib_fifo_v1_0_19 -l blk_mem_gen_v8_4_8 -l lib_bmg_v1_0_17 -l lib_srl_fifo_v1_0_4 -l axi_datamover_v5_1_33 -l axi_vdma_v6_3_19 -l axis_infrastructure_v1_1_1 -l axis_register_slice_v1_1_31 -l interrupt_control_v3_1_5 -l axi_gpio_v2_0_33 -l v_vid_in_axi4s_v5_0_4 -l v_tc_v6_2_8 -l v_tc_v6_1_14 -l v_vid_in_axi4s_v4_0_11 -l v_axi4s_vid_out_v4_0_18 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l axis_dwidth_converter_v1_1_30 -l axi_protocol_converter_v2_1_31 -l axi_clock_converter_v2_1_30 -l axi_dwidth_converter_v2_1_31 \
"../../../../base.gen/sources_1/bd/base/ipshared/9746/hdl/v_vid_in_axi4s_v5_0_vl_rfs.v" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/b28c/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/a4a8/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/3c6d/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/7611/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/1376/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" "+incdir+/tools/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xlconcat_v2_1_6 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l processing_system7_vip_v1_0_19 -l generic_baseblocks_v2_1_2 -l axi_register_slice_v2_1_31 -l fifo_generator_v13_2_10 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l axi_lite_ipif_v3_0_4 -l axi_intc_v4_1_19 -l lib_pkg_v1_0_4 -l lib_fifo_v1_0_19 -l blk_mem_gen_v8_4_8 -l lib_bmg_v1_0_17 -l lib_srl_fifo_v1_0_4 -l axi_datamover_v5_1_33 -l axi_vdma_v6_3_19 -l axis_infrastructure_v1_1_1 -l axis_register_slice_v1_1_31 -l interrupt_control_v3_1_5 -l axi_gpio_v2_0_33 -l v_vid_in_axi4s_v5_0_4 -l v_tc_v6_2_8 -l v_tc_v6_1_14 -l v_vid_in_axi4s_v4_0_11 -l v_axi4s_vid_out_v4_0_18 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l axis_dwidth_converter_v1_1_30 -l axi_protocol_converter_v2_1_31 -l axi_clock_converter_v2_1_30 -l axi_dwidth_converter_v2_1_31 \
"../../../../base.gen/sources_1/bd/base/ip/base_v_vid_in_axi4s_0_0/sim/base_v_vid_in_axi4s_0_0.v" \

vcom -work v_tc_v6_2_8 -93  -incr \
"../../../../base.gen/sources_1/bd/base/ipshared/5959/hdl/v_tc_v6_2_vh_rfs.vhd" \

vcom -work xil_defaultlib -93  -incr \
"../../../../base.gen/sources_1/bd/base/ip/base_vtc_in_0/sim/base_vtc_in_0.vhd" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/b28c/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/a4a8/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/3c6d/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/7611/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/1376/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" "+incdir+/tools/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xlconcat_v2_1_6 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l processing_system7_vip_v1_0_19 -l generic_baseblocks_v2_1_2 -l axi_register_slice_v2_1_31 -l fifo_generator_v13_2_10 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l axi_lite_ipif_v3_0_4 -l axi_intc_v4_1_19 -l lib_pkg_v1_0_4 -l lib_fifo_v1_0_19 -l blk_mem_gen_v8_4_8 -l lib_bmg_v1_0_17 -l lib_srl_fifo_v1_0_4 -l axi_datamover_v5_1_33 -l axi_vdma_v6_3_19 -l axis_infrastructure_v1_1_1 -l axis_register_slice_v1_1_31 -l interrupt_control_v3_1_5 -l axi_gpio_v2_0_33 -l v_vid_in_axi4s_v5_0_4 -l v_tc_v6_2_8 -l v_tc_v6_1_14 -l v_vid_in_axi4s_v4_0_11 -l v_axi4s_vid_out_v4_0_18 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l axis_dwidth_converter_v1_1_30 -l axi_protocol_converter_v2_1_31 -l axi_clock_converter_v2_1_30 -l axi_dwidth_converter_v2_1_31 \
"../../../../base.gen/sources_1/bd/base/ipshared/7611/hdl/verilog/pixel_pack_control_s_axi.v" \
"../../../../base.gen/sources_1/bd/base/ipshared/7611/hdl/verilog/pixel_pack_flow_control_loop_pipe_sequential_init.v" \
"../../../../base.gen/sources_1/bd/base/ipshared/7611/hdl/verilog/pixel_pack_hls_deadlock_idx0_monitor.v" \
"../../../../base.gen/sources_1/bd/base/ipshared/7611/hdl/verilog/pixel_pack_hls_deadlock_idx1_monitor.v" \
"../../../../base.gen/sources_1/bd/base/ipshared/7611/hdl/verilog/pixel_pack_hls_deadlock_idx2_monitor.v" \
"../../../../base.gen/sources_1/bd/base/ipshared/7611/hdl/verilog/pixel_pack_hls_deadlock_idx3_monitor.v" \
"../../../../base.gen/sources_1/bd/base/ipshared/7611/hdl/verilog/pixel_pack_hls_deadlock_idx4_monitor.v" \
"../../../../base.gen/sources_1/bd/base/ipshared/7611/hdl/verilog/pixel_pack_hls_deadlock_idx5_monitor.v" \
"../../../../base.gen/sources_1/bd/base/ipshared/7611/hdl/verilog/pixel_pack_pixel_pack_Pipeline_VITIS_LOOP_21_1.v" \
"../../../../base.gen/sources_1/bd/base/ipshared/7611/hdl/verilog/pixel_pack_pixel_pack_Pipeline_VITIS_LOOP_47_4.v" \
"../../../../base.gen/sources_1/bd/base/ipshared/7611/hdl/verilog/pixel_pack_pixel_pack_Pipeline_VITIS_LOOP_62_5.v" \
"../../../../base.gen/sources_1/bd/base/ipshared/7611/hdl/verilog/pixel_pack_pixel_pack_Pipeline_VITIS_LOOP_84_7.v" \
"../../../../base.gen/sources_1/bd/base/ipshared/7611/hdl/verilog/pixel_pack_pixel_pack_Pipeline_VITIS_LOOP_101_9.v" \
"../../../../base.gen/sources_1/bd/base/ipshared/7611/hdl/verilog/pixel_pack_regslice_both.v" \
"../../../../base.gen/sources_1/bd/base/ipshared/7611/hdl/verilog/pixel_pack.v" \
"../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/sim/base_pixel_pack_0.v" \
"../../../../base.gen/sources_1/bd/base/ip/base_axis_register_slice_0_1/sim/base_axis_register_slice_0_1.v" \
"../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/sim/base_color_convert_1.v" \
"../../../../base.gen/sources_1/bd/base/ipshared/9097/src/mmcme2_drp.v" \

vcom -work xil_defaultlib -93  -incr \
"../../../../base.gen/sources_1/bd/base/ipshared/9097/src/axi_dynclk_S00_AXI.vhd" \
"../../../../base.gen/sources_1/bd/base/ipshared/9097/src/axi_dynclk.vhd" \
"../../../../base.gen/sources_1/bd/base/ip/base_axi_dynclk_0/sim/base_axi_dynclk_0.vhd" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/b28c/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/a4a8/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/3c6d/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/7611/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/1376/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" "+incdir+/tools/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xlconcat_v2_1_6 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l processing_system7_vip_v1_0_19 -l generic_baseblocks_v2_1_2 -l axi_register_slice_v2_1_31 -l fifo_generator_v13_2_10 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l axi_lite_ipif_v3_0_4 -l axi_intc_v4_1_19 -l lib_pkg_v1_0_4 -l lib_fifo_v1_0_19 -l blk_mem_gen_v8_4_8 -l lib_bmg_v1_0_17 -l lib_srl_fifo_v1_0_4 -l axi_datamover_v5_1_33 -l axi_vdma_v6_3_19 -l axis_infrastructure_v1_1_1 -l axis_register_slice_v1_1_31 -l interrupt_control_v3_1_5 -l axi_gpio_v2_0_33 -l v_vid_in_axi4s_v5_0_4 -l v_tc_v6_2_8 -l v_tc_v6_1_14 -l v_vid_in_axi4s_v4_0_11 -l v_axi4s_vid_out_v4_0_18 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l axis_dwidth_converter_v1_1_30 -l axi_protocol_converter_v2_1_31 -l axi_clock_converter_v2_1_30 -l axi_dwidth_converter_v2_1_31 \
"../../../../base.gen/sources_1/bd/base/ip/base_color_swap_0_1/sim/base_color_swap_0_1.v" \

vcom -work xil_defaultlib -93  -incr \
"../../../../base.gen/sources_1/bd/base/ip/base_hdmi_out_hpd_video_0/sim/base_hdmi_out_hpd_video_0.vhd" \
"../../../../base.gen/sources_1/bd/base/ipshared/bd5a/src/ClockGen.vhd" \
"../../../../base.gen/sources_1/bd/base/ipshared/bd5a/src/OutputSERDES.vhd" \
"../../../../base.gen/sources_1/bd/base/ipshared/bd5a/src/TMDS_Encoder.vhd" \
"../../../../base.gen/sources_1/bd/base/ipshared/bd5a/src/rgb2dvi.vhd" \
"../../../../base.gen/sources_1/bd/base/ip/base_rgb2dvi_0_0/sim/base_rgb2dvi_0_0.vhd" \

vcom -work v_tc_v6_1_14 -93  -incr \
"../../../../base.gen/sources_1/bd/base/ipshared/fd54/hdl/v_tc_v6_1_vh_rfs.vhd" \

vlog -work v_vid_in_axi4s_v4_0_11  -incr -v2k5 "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/b28c/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/a4a8/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/3c6d/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/7611/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/1376/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" "+incdir+/tools/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xlconcat_v2_1_6 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l processing_system7_vip_v1_0_19 -l generic_baseblocks_v2_1_2 -l axi_register_slice_v2_1_31 -l fifo_generator_v13_2_10 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l axi_lite_ipif_v3_0_4 -l axi_intc_v4_1_19 -l lib_pkg_v1_0_4 -l lib_fifo_v1_0_19 -l blk_mem_gen_v8_4_8 -l lib_bmg_v1_0_17 -l lib_srl_fifo_v1_0_4 -l axi_datamover_v5_1_33 -l axi_vdma_v6_3_19 -l axis_infrastructure_v1_1_1 -l axis_register_slice_v1_1_31 -l interrupt_control_v3_1_5 -l axi_gpio_v2_0_33 -l v_vid_in_axi4s_v5_0_4 -l v_tc_v6_2_8 -l v_tc_v6_1_14 -l v_vid_in_axi4s_v4_0_11 -l v_axi4s_vid_out_v4_0_18 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l axis_dwidth_converter_v1_1_30 -l axi_protocol_converter_v2_1_31 -l axi_clock_converter_v2_1_30 -l axi_dwidth_converter_v2_1_31 \
"../../../../base.gen/sources_1/bd/base/ipshared/4705/hdl/v_vid_in_axi4s_v4_0_vl_rfs.v" \

vlog -work v_axi4s_vid_out_v4_0_18  -incr -v2k5 "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/b28c/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/a4a8/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/3c6d/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/7611/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/1376/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" "+incdir+/tools/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xlconcat_v2_1_6 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l processing_system7_vip_v1_0_19 -l generic_baseblocks_v2_1_2 -l axi_register_slice_v2_1_31 -l fifo_generator_v13_2_10 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l axi_lite_ipif_v3_0_4 -l axi_intc_v4_1_19 -l lib_pkg_v1_0_4 -l lib_fifo_v1_0_19 -l blk_mem_gen_v8_4_8 -l lib_bmg_v1_0_17 -l lib_srl_fifo_v1_0_4 -l axi_datamover_v5_1_33 -l axi_vdma_v6_3_19 -l axis_infrastructure_v1_1_1 -l axis_register_slice_v1_1_31 -l interrupt_control_v3_1_5 -l axi_gpio_v2_0_33 -l v_vid_in_axi4s_v5_0_4 -l v_tc_v6_2_8 -l v_tc_v6_1_14 -l v_vid_in_axi4s_v4_0_11 -l v_axi4s_vid_out_v4_0_18 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l axis_dwidth_converter_v1_1_30 -l axi_protocol_converter_v2_1_31 -l axi_clock_converter_v2_1_30 -l axi_dwidth_converter_v2_1_31 \
"../../../../base.gen/sources_1/bd/base/ipshared/52cd/hdl/v_axi4s_vid_out_v4_0_vl_rfs.v" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/b28c/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/a4a8/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/3c6d/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/7611/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/1376/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" "+incdir+/tools/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xlconcat_v2_1_6 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l processing_system7_vip_v1_0_19 -l generic_baseblocks_v2_1_2 -l axi_register_slice_v2_1_31 -l fifo_generator_v13_2_10 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l axi_lite_ipif_v3_0_4 -l axi_intc_v4_1_19 -l lib_pkg_v1_0_4 -l lib_fifo_v1_0_19 -l blk_mem_gen_v8_4_8 -l lib_bmg_v1_0_17 -l lib_srl_fifo_v1_0_4 -l axi_datamover_v5_1_33 -l axi_vdma_v6_3_19 -l axis_infrastructure_v1_1_1 -l axis_register_slice_v1_1_31 -l interrupt_control_v3_1_5 -l axi_gpio_v2_0_33 -l v_vid_in_axi4s_v5_0_4 -l v_tc_v6_2_8 -l v_tc_v6_1_14 -l v_vid_in_axi4s_v4_0_11 -l v_axi4s_vid_out_v4_0_18 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l axis_dwidth_converter_v1_1_30 -l axi_protocol_converter_v2_1_31 -l axi_clock_converter_v2_1_30 -l axi_dwidth_converter_v2_1_31 \
"../../../../base.gen/sources_1/bd/base/ip/base_v_axi4s_vid_out_0_0/sim/base_v_axi4s_vid_out_0_0.v" \

vcom -work xil_defaultlib -93  -incr \
"../../../../base.gen/sources_1/bd/base/ip/base_vtc_out_0/sim/base_vtc_out_0.vhd" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/b28c/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/a4a8/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/3c6d/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/7611/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/1376/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" "+incdir+/tools/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xlconcat_v2_1_6 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l processing_system7_vip_v1_0_19 -l generic_baseblocks_v2_1_2 -l axi_register_slice_v2_1_31 -l fifo_generator_v13_2_10 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l axi_lite_ipif_v3_0_4 -l axi_intc_v4_1_19 -l lib_pkg_v1_0_4 -l lib_fifo_v1_0_19 -l blk_mem_gen_v8_4_8 -l lib_bmg_v1_0_17 -l lib_srl_fifo_v1_0_4 -l axi_datamover_v5_1_33 -l axi_vdma_v6_3_19 -l axis_infrastructure_v1_1_1 -l axis_register_slice_v1_1_31 -l interrupt_control_v3_1_5 -l axi_gpio_v2_0_33 -l v_vid_in_axi4s_v5_0_4 -l v_tc_v6_2_8 -l v_tc_v6_1_14 -l v_vid_in_axi4s_v4_0_11 -l v_axi4s_vid_out_v4_0_18 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l axis_dwidth_converter_v1_1_30 -l axi_protocol_converter_v2_1_31 -l axi_clock_converter_v2_1_30 -l axi_dwidth_converter_v2_1_31 \
"../../../../base.gen/sources_1/bd/base/ipshared/1376/hdl/verilog/pixel_unpack_control_s_axi.v" \
"../../../../base.gen/sources_1/bd/base/ipshared/1376/hdl/verilog/pixel_unpack_flow_control_loop_pipe_sequential_init.v" \
"../../../../base.gen/sources_1/bd/base/ipshared/1376/hdl/verilog/pixel_unpack_hls_deadlock_idx0_monitor.v" \
"../../../../base.gen/sources_1/bd/base/ipshared/1376/hdl/verilog/pixel_unpack_hls_deadlock_idx1_monitor.v" \
"../../../../base.gen/sources_1/bd/base/ipshared/1376/hdl/verilog/pixel_unpack_hls_deadlock_idx2_monitor.v" \
"../../../../base.gen/sources_1/bd/base/ipshared/1376/hdl/verilog/pixel_unpack_hls_deadlock_idx3_monitor.v" \
"../../../../base.gen/sources_1/bd/base/ipshared/1376/hdl/verilog/pixel_unpack_hls_deadlock_idx4_monitor.v" \
"../../../../base.gen/sources_1/bd/base/ipshared/1376/hdl/verilog/pixel_unpack_hls_deadlock_idx5_monitor.v" \
"../../../../base.gen/sources_1/bd/base/ipshared/1376/hdl/verilog/pixel_unpack_pixel_unpack_Pipeline_VITIS_LOOP_19_1.v" \
"../../../../base.gen/sources_1/bd/base/ipshared/1376/hdl/verilog/pixel_unpack_pixel_unpack_Pipeline_VITIS_LOOP_40_4.v" \
"../../../../base.gen/sources_1/bd/base/ipshared/1376/hdl/verilog/pixel_unpack_pixel_unpack_Pipeline_VITIS_LOOP_51_5.v" \
"../../../../base.gen/sources_1/bd/base/ipshared/1376/hdl/verilog/pixel_unpack_pixel_unpack_Pipeline_VITIS_LOOP_68_7.v" \
"../../../../base.gen/sources_1/bd/base/ipshared/1376/hdl/verilog/pixel_unpack_pixel_unpack_Pipeline_VITIS_LOOP_85_9.v" \
"../../../../base.gen/sources_1/bd/base/ipshared/1376/hdl/verilog/pixel_unpack_regslice_both.v" \
"../../../../base.gen/sources_1/bd/base/ipshared/1376/hdl/verilog/pixel_unpack.v" \
"../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/sim/base_pixel_unpack_0.v" \

vcom -work xil_defaultlib -93  -incr \
"../../../../base.gen/sources_1/bd/base/ip/base_proc_sys_reset_pixelclk_0/sim/base_proc_sys_reset_pixelclk_0.vhd" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/b28c/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/a4a8/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/3c6d/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/7611/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/1376/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" "+incdir+/tools/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xlconcat_v2_1_6 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l processing_system7_vip_v1_0_19 -l generic_baseblocks_v2_1_2 -l axi_register_slice_v2_1_31 -l fifo_generator_v13_2_10 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l axi_lite_ipif_v3_0_4 -l axi_intc_v4_1_19 -l lib_pkg_v1_0_4 -l lib_fifo_v1_0_19 -l blk_mem_gen_v8_4_8 -l lib_bmg_v1_0_17 -l lib_srl_fifo_v1_0_4 -l axi_datamover_v5_1_33 -l axi_vdma_v6_3_19 -l axis_infrastructure_v1_1_1 -l axis_register_slice_v1_1_31 -l interrupt_control_v3_1_5 -l axi_gpio_v2_0_33 -l v_vid_in_axi4s_v5_0_4 -l v_tc_v6_2_8 -l v_tc_v6_1_14 -l v_vid_in_axi4s_v4_0_11 -l v_axi4s_vid_out_v4_0_18 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l axis_dwidth_converter_v1_1_30 -l axi_protocol_converter_v2_1_31 -l axi_clock_converter_v2_1_30 -l axi_dwidth_converter_v2_1_31 \
"../../../../base.gen/sources_1/bd/base/ip/base_xlconcat_0_0/sim/base_xlconcat_0_0.v" \
"../../../../base.gen/sources_1/bd/base/ip/base_xlconcat_0_1/sim/base_xlconcat_0_1.v" \

vcom -work axi_sg_v4_1_18 -93  -incr \
"../../../../base.gen/sources_1/bd/base/ipshared/6f54/hdl/axi_sg_v4_1_rfs.vhd" \

vcom -work axi_dma_v7_1_32 -93  -incr \
"../../../../base.gen/sources_1/bd/base/ipshared/8830/hdl/axi_dma_v7_1_vh_rfs.vhd" \

vcom -work xil_defaultlib -93  -incr \
"../../../../base.gen/sources_1/bd/base/ip/base_axi_dma_0_0/sim/base_axi_dma_0_0.vhd" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/b28c/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/a4a8/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/3c6d/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/7611/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/1376/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" "+incdir+/tools/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xlconcat_v2_1_6 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l processing_system7_vip_v1_0_19 -l generic_baseblocks_v2_1_2 -l axi_register_slice_v2_1_31 -l fifo_generator_v13_2_10 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l axi_lite_ipif_v3_0_4 -l axi_intc_v4_1_19 -l lib_pkg_v1_0_4 -l lib_fifo_v1_0_19 -l blk_mem_gen_v8_4_8 -l lib_bmg_v1_0_17 -l lib_srl_fifo_v1_0_4 -l axi_datamover_v5_1_33 -l axi_vdma_v6_3_19 -l axis_infrastructure_v1_1_1 -l axis_register_slice_v1_1_31 -l interrupt_control_v3_1_5 -l axi_gpio_v2_0_33 -l v_vid_in_axi4s_v5_0_4 -l v_tc_v6_2_8 -l v_tc_v6_1_14 -l v_vid_in_axi4s_v4_0_11 -l v_axi4s_vid_out_v4_0_18 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l axis_dwidth_converter_v1_1_30 -l axi_protocol_converter_v2_1_31 -l axi_clock_converter_v2_1_30 -l axi_dwidth_converter_v2_1_31 \
"../../../../base.gen/sources_1/bd/base/ip/base_render_24_0_0/sim/base_render_24_0_0.v" \

vlog -work axis_dwidth_converter_v1_1_30  -incr -v2k5 "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/b28c/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/a4a8/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/3c6d/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/7611/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/1376/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" "+incdir+/tools/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xlconcat_v2_1_6 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l processing_system7_vip_v1_0_19 -l generic_baseblocks_v2_1_2 -l axi_register_slice_v2_1_31 -l fifo_generator_v13_2_10 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l axi_lite_ipif_v3_0_4 -l axi_intc_v4_1_19 -l lib_pkg_v1_0_4 -l lib_fifo_v1_0_19 -l blk_mem_gen_v8_4_8 -l lib_bmg_v1_0_17 -l lib_srl_fifo_v1_0_4 -l axi_datamover_v5_1_33 -l axi_vdma_v6_3_19 -l axis_infrastructure_v1_1_1 -l axis_register_slice_v1_1_31 -l interrupt_control_v3_1_5 -l axi_gpio_v2_0_33 -l v_vid_in_axi4s_v5_0_4 -l v_tc_v6_2_8 -l v_tc_v6_1_14 -l v_vid_in_axi4s_v4_0_11 -l v_axi4s_vid_out_v4_0_18 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l axis_dwidth_converter_v1_1_30 -l axi_protocol_converter_v2_1_31 -l axi_clock_converter_v2_1_30 -l axi_dwidth_converter_v2_1_31 \
"../../../../base.gen/sources_1/bd/base/ipshared/411b/hdl/axis_dwidth_converter_v1_1_vl_rfs.v" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/b28c/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/a4a8/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/3c6d/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/7611/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/1376/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" "+incdir+/tools/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xlconcat_v2_1_6 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l processing_system7_vip_v1_0_19 -l generic_baseblocks_v2_1_2 -l axi_register_slice_v2_1_31 -l fifo_generator_v13_2_10 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l axi_lite_ipif_v3_0_4 -l axi_intc_v4_1_19 -l lib_pkg_v1_0_4 -l lib_fifo_v1_0_19 -l blk_mem_gen_v8_4_8 -l lib_bmg_v1_0_17 -l lib_srl_fifo_v1_0_4 -l axi_datamover_v5_1_33 -l axi_vdma_v6_3_19 -l axis_infrastructure_v1_1_1 -l axis_register_slice_v1_1_31 -l interrupt_control_v3_1_5 -l axi_gpio_v2_0_33 -l v_vid_in_axi4s_v5_0_4 -l v_tc_v6_2_8 -l v_tc_v6_1_14 -l v_vid_in_axi4s_v4_0_11 -l v_axi4s_vid_out_v4_0_18 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l axis_dwidth_converter_v1_1_30 -l axi_protocol_converter_v2_1_31 -l axi_clock_converter_v2_1_30 -l axi_dwidth_converter_v2_1_31 \
"../../../../base.gen/sources_1/bd/base/ip/base_axis_dwidth_converter_0_0/sim/base_axis_dwidth_converter_0_0.v" \
"../../../../base.gen/sources_1/bd/base/ip/base_button_0_0/sim/base_button_0_0.v" \
"../../../../base.gen/sources_1/bd/base/ip/base_s00_regslice_22/sim/base_s00_regslice_22.v" \

vlog -work axi_protocol_converter_v2_1_31  -incr -v2k5 "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/b28c/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/a4a8/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/3c6d/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/7611/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/1376/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" "+incdir+/tools/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xlconcat_v2_1_6 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l processing_system7_vip_v1_0_19 -l generic_baseblocks_v2_1_2 -l axi_register_slice_v2_1_31 -l fifo_generator_v13_2_10 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l axi_lite_ipif_v3_0_4 -l axi_intc_v4_1_19 -l lib_pkg_v1_0_4 -l lib_fifo_v1_0_19 -l blk_mem_gen_v8_4_8 -l lib_bmg_v1_0_17 -l lib_srl_fifo_v1_0_4 -l axi_datamover_v5_1_33 -l axi_vdma_v6_3_19 -l axis_infrastructure_v1_1_1 -l axis_register_slice_v1_1_31 -l interrupt_control_v3_1_5 -l axi_gpio_v2_0_33 -l v_vid_in_axi4s_v5_0_4 -l v_tc_v6_2_8 -l v_tc_v6_1_14 -l v_vid_in_axi4s_v4_0_11 -l v_axi4s_vid_out_v4_0_18 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l axis_dwidth_converter_v1_1_30 -l axi_protocol_converter_v2_1_31 -l axi_clock_converter_v2_1_30 -l axi_dwidth_converter_v2_1_31 \
"../../../../base.gen/sources_1/bd/base/ipshared/3c06/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/b28c/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/a4a8/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/3c6d/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/7611/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/1376/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" "+incdir+/tools/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xlconcat_v2_1_6 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l processing_system7_vip_v1_0_19 -l generic_baseblocks_v2_1_2 -l axi_register_slice_v2_1_31 -l fifo_generator_v13_2_10 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l axi_lite_ipif_v3_0_4 -l axi_intc_v4_1_19 -l lib_pkg_v1_0_4 -l lib_fifo_v1_0_19 -l blk_mem_gen_v8_4_8 -l lib_bmg_v1_0_17 -l lib_srl_fifo_v1_0_4 -l axi_datamover_v5_1_33 -l axi_vdma_v6_3_19 -l axis_infrastructure_v1_1_1 -l axis_register_slice_v1_1_31 -l interrupt_control_v3_1_5 -l axi_gpio_v2_0_33 -l v_vid_in_axi4s_v5_0_4 -l v_tc_v6_2_8 -l v_tc_v6_1_14 -l v_vid_in_axi4s_v4_0_11 -l v_axi4s_vid_out_v4_0_18 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l axis_dwidth_converter_v1_1_30 -l axi_protocol_converter_v2_1_31 -l axi_clock_converter_v2_1_30 -l axi_dwidth_converter_v2_1_31 \
"../../../../base.gen/sources_1/bd/base/ip/base_auto_pc_4/sim/base_auto_pc_4.v" \
"../../../../base.gen/sources_1/bd/base/ip/base_m00_regslice_22/sim/base_m00_regslice_22.v" \
"../../../../base.gen/sources_1/bd/base/ip/base_auto_pc_0/sim/base_auto_pc_0.v" \
"../../../../base.gen/sources_1/bd/base/ip/base_m01_regslice_22/sim/base_m01_regslice_22.v" \
"../../../../base.gen/sources_1/bd/base/ip/base_m02_regslice_22/sim/base_m02_regslice_22.v" \
"../../../../base.gen/sources_1/bd/base/ip/base_auto_pc_1/sim/base_auto_pc_1.v" \
"../../../../base.gen/sources_1/bd/base/ip/base_m03_regslice_22/sim/base_m03_regslice_22.v" \
"../../../../base.gen/sources_1/bd/base/ip/base_auto_pc_2/sim/base_auto_pc_2.v" \
"../../../../base.gen/sources_1/bd/base/ip/base_m04_regslice_7/sim/base_m04_regslice_7.v" \
"../../../../base.gen/sources_1/bd/base/ip/base_auto_pc_3/sim/base_auto_pc_3.v" \
"../../../../base.gen/sources_1/bd/base/ip/base_s00_regslice_23/sim/base_s00_regslice_23.v" \
"../../../../base.gen/sources_1/bd/base/ip/base_auto_pc_5/sim/base_auto_pc_5.v" \
"../../../../base.gen/sources_1/bd/base/ip/base_m00_regslice_23/sim/base_m00_regslice_23.v" \
"../../../../base.gen/sources_1/bd/base/ip/base_m01_regslice_23/sim/base_m01_regslice_23.v" \

vlog -work axi_clock_converter_v2_1_30  -incr -v2k5 "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/b28c/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/a4a8/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/3c6d/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/7611/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/1376/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" "+incdir+/tools/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xlconcat_v2_1_6 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l processing_system7_vip_v1_0_19 -l generic_baseblocks_v2_1_2 -l axi_register_slice_v2_1_31 -l fifo_generator_v13_2_10 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l axi_lite_ipif_v3_0_4 -l axi_intc_v4_1_19 -l lib_pkg_v1_0_4 -l lib_fifo_v1_0_19 -l blk_mem_gen_v8_4_8 -l lib_bmg_v1_0_17 -l lib_srl_fifo_v1_0_4 -l axi_datamover_v5_1_33 -l axi_vdma_v6_3_19 -l axis_infrastructure_v1_1_1 -l axis_register_slice_v1_1_31 -l interrupt_control_v3_1_5 -l axi_gpio_v2_0_33 -l v_vid_in_axi4s_v5_0_4 -l v_tc_v6_2_8 -l v_tc_v6_1_14 -l v_vid_in_axi4s_v4_0_11 -l v_axi4s_vid_out_v4_0_18 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l axis_dwidth_converter_v1_1_30 -l axi_protocol_converter_v2_1_31 -l axi_clock_converter_v2_1_30 -l axi_dwidth_converter_v2_1_31 \
"../../../../base.gen/sources_1/bd/base/ipshared/80bf/hdl/axi_clock_converter_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/b28c/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/a4a8/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/3c6d/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/7611/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/1376/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" "+incdir+/tools/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xlconcat_v2_1_6 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l processing_system7_vip_v1_0_19 -l generic_baseblocks_v2_1_2 -l axi_register_slice_v2_1_31 -l fifo_generator_v13_2_10 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l axi_lite_ipif_v3_0_4 -l axi_intc_v4_1_19 -l lib_pkg_v1_0_4 -l lib_fifo_v1_0_19 -l blk_mem_gen_v8_4_8 -l lib_bmg_v1_0_17 -l lib_srl_fifo_v1_0_4 -l axi_datamover_v5_1_33 -l axi_vdma_v6_3_19 -l axis_infrastructure_v1_1_1 -l axis_register_slice_v1_1_31 -l interrupt_control_v3_1_5 -l axi_gpio_v2_0_33 -l v_vid_in_axi4s_v5_0_4 -l v_tc_v6_2_8 -l v_tc_v6_1_14 -l v_vid_in_axi4s_v4_0_11 -l v_axi4s_vid_out_v4_0_18 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l axis_dwidth_converter_v1_1_30 -l axi_protocol_converter_v2_1_31 -l axi_clock_converter_v2_1_30 -l axi_dwidth_converter_v2_1_31 \
"../../../../base.gen/sources_1/bd/base/ip/base_auto_cc_0/sim/base_auto_cc_0.v" \
"../../../../base.gen/sources_1/bd/base/ip/base_m02_regslice_23/sim/base_m02_regslice_23.v" \
"../../../../base.gen/sources_1/bd/base/ip/base_auto_cc_1/sim/base_auto_cc_1.v" \
"../../../../base.gen/sources_1/bd/base/ip/base_m03_regslice_23/sim/base_m03_regslice_23.v" \
"../../../../base.gen/sources_1/bd/base/ip/base_m04_regslice_8/sim/base_m04_regslice_8.v" \
"../../../../base.gen/sources_1/bd/base/ip/base_m05_regslice_0/sim/base_m05_regslice_0.v" \
"../../../../base.gen/sources_1/bd/base/ip/base_m06_regslice_0/sim/base_m06_regslice_0.v" \
"../../../../base.gen/sources_1/bd/base/ip/base_auto_cc_2/sim/base_auto_cc_2.v" \
"../../../../base.gen/sources_1/bd/base/ip/base_m07_regslice_0/sim/base_m07_regslice_0.v" \
"../../../../base.gen/sources_1/bd/base/ip/base_auto_cc_3/sim/base_auto_cc_3.v" \
"../../../../base.gen/sources_1/bd/base/ip/base_m08_regslice_0/sim/base_m08_regslice_0.v" \
"../../../../base.gen/sources_1/bd/base/ip/base_m09_regslice_0/sim/base_m09_regslice_0.v" \

vlog -work axi_dwidth_converter_v2_1_31  -incr -v2k5 "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/b28c/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/a4a8/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/3c6d/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/7611/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/1376/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" "+incdir+/tools/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xlconcat_v2_1_6 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l processing_system7_vip_v1_0_19 -l generic_baseblocks_v2_1_2 -l axi_register_slice_v2_1_31 -l fifo_generator_v13_2_10 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l axi_lite_ipif_v3_0_4 -l axi_intc_v4_1_19 -l lib_pkg_v1_0_4 -l lib_fifo_v1_0_19 -l blk_mem_gen_v8_4_8 -l lib_bmg_v1_0_17 -l lib_srl_fifo_v1_0_4 -l axi_datamover_v5_1_33 -l axi_vdma_v6_3_19 -l axis_infrastructure_v1_1_1 -l axis_register_slice_v1_1_31 -l interrupt_control_v3_1_5 -l axi_gpio_v2_0_33 -l v_vid_in_axi4s_v5_0_4 -l v_tc_v6_2_8 -l v_tc_v6_1_14 -l v_vid_in_axi4s_v4_0_11 -l v_axi4s_vid_out_v4_0_18 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l axis_dwidth_converter_v1_1_30 -l axi_protocol_converter_v2_1_31 -l axi_clock_converter_v2_1_30 -l axi_dwidth_converter_v2_1_31 \
"../../../../base.gen/sources_1/bd/base/ipshared/14b9/hdl/axi_dwidth_converter_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/ec67/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/b28c/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/a4a8/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/434f/hdl" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/3c6d/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/7611/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ipshared/1376/hdl/verilog" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_0/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_pack_0/drivers/pixel_pack_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_color_convert_1/drivers/color_convert_v1_0/src" "+incdir+../../../../base.gen/sources_1/bd/base/ip/base_pixel_unpack_0/drivers/pixel_unpack_v1_0/src" "+incdir+/tools/Xilinx/Vivado/2024.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xlconcat_v2_1_6 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_17 -l processing_system7_vip_v1_0_19 -l generic_baseblocks_v2_1_2 -l axi_register_slice_v2_1_31 -l fifo_generator_v13_2_10 -l axi_data_fifo_v2_1_30 -l axi_crossbar_v2_1_32 -l lib_cdc_v1_0_3 -l proc_sys_reset_v5_0_15 -l axi_lite_ipif_v3_0_4 -l axi_intc_v4_1_19 -l lib_pkg_v1_0_4 -l lib_fifo_v1_0_19 -l blk_mem_gen_v8_4_8 -l lib_bmg_v1_0_17 -l lib_srl_fifo_v1_0_4 -l axi_datamover_v5_1_33 -l axi_vdma_v6_3_19 -l axis_infrastructure_v1_1_1 -l axis_register_slice_v1_1_31 -l interrupt_control_v3_1_5 -l axi_gpio_v2_0_33 -l v_vid_in_axi4s_v5_0_4 -l v_tc_v6_2_8 -l v_tc_v6_1_14 -l v_vid_in_axi4s_v4_0_11 -l v_axi4s_vid_out_v4_0_18 -l axi_sg_v4_1_18 -l axi_dma_v7_1_32 -l axis_dwidth_converter_v1_1_30 -l axi_protocol_converter_v2_1_31 -l axi_clock_converter_v2_1_30 -l axi_dwidth_converter_v2_1_31 \
"../../../../base.gen/sources_1/bd/base/ip/base_auto_us_0/sim/base_auto_us_0.v" \
"../../../../base.gen/sources_1/bd/base/ip/base_auto_pc_6/sim/base_auto_pc_6.v" \
"../../../../base.gen/sources_1/bd/base/ip/base_auto_pc_7/sim/base_auto_pc_7.v" \
"../../../../base.gen/sources_1/bd/base/ip/base_auto_pc_8/sim/base_auto_pc_8.v" \
"../../../../base.gen/sources_1/bd/base/ip/base_auto_us_1/sim/base_auto_us_1.v" \
"../../../../base.gen/sources_1/bd/base/sim/base.v" \

vlog -work xil_defaultlib \
"glbl.v"

