// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module main_process_rotate_move (
        ap_clk,
        ap_rst,
        i_a11_val,
        i_a12_val,
        i_a13_val,
        i_a21_val,
        i_a22_val,
        i_a23_val,
        i_a31_val,
        i_a32_val,
        i_a33_val,
        i_p1_val,
        i_p2_val,
        i_p3_val,
        i_x_val,
        i_y_val,
        i_z_val,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [15:0] i_a11_val;
input  [15:0] i_a12_val;
input  [15:0] i_a13_val;
input  [15:0] i_a21_val;
input  [15:0] i_a22_val;
input  [15:0] i_a23_val;
input  [15:0] i_a31_val;
input  [15:0] i_a32_val;
input  [15:0] i_a33_val;
input  [18:0] i_p1_val;
input  [18:0] i_p2_val;
input  [18:0] i_p3_val;
input  [17:0] i_x_val;
input  [17:0] i_y_val;
input  [17:0] i_z_val;
output  [25:0] ap_return_0;
output  [25:0] ap_return_1;
output  [25:0] ap_return_2;
input   ap_ce;

reg[25:0] ap_return_0;
reg[25:0] ap_return_1;
reg[25:0] ap_return_2;

reg   [17:0] i_y_val_read_reg_400;
wire    ap_block_pp0_stage0_11001;
reg   [18:0] i_p3_val_read_reg_405;
reg   [18:0] i_p3_val_read_reg_405_pp0_iter1_reg;
reg   [18:0] i_p2_val_read_reg_410;
reg   [18:0] i_p2_val_read_reg_410_pp0_iter1_reg;
reg   [18:0] i_p1_val_read_reg_415;
reg   [18:0] i_p1_val_read_reg_415_pp0_iter1_reg;
reg  signed [15:0] i_a32_val_read_reg_420;
reg  signed [15:0] i_a22_val_read_reg_425;
reg  signed [15:0] i_a12_val_read_reg_430;
wire   [33:0] zext_ln14_fu_150_p1;
wire   [33:0] zext_ln14_2_fu_158_p1;
wire   [33:0] mul_ln14_1_fu_184_p2;
reg  signed [33:0] mul_ln14_1_reg_479;
wire   [33:0] mul_ln15_1_fu_193_p2;
reg  signed [33:0] mul_ln15_1_reg_484;
wire   [33:0] mul_ln16_1_fu_202_p2;
reg  signed [33:0] mul_ln16_1_reg_489;
wire    ap_block_pp0_stage0;
wire   [17:0] mul_ln14_1_fu_184_p0;
wire   [33:0] zext_ln14_1_fu_181_p1;
wire   [17:0] mul_ln15_1_fu_193_p0;
wire   [17:0] mul_ln16_1_fu_202_p0;
wire  signed [32:0] shl_ln_fu_211_p3;
wire  signed [32:0] shl_ln1_fu_225_p3;
wire  signed [32:0] shl_ln2_fu_239_p3;
wire  signed [34:0] grp_fu_346_p3;
wire  signed [34:0] grp_fu_355_p3;
wire  signed [35:0] sext_ln14_8_fu_253_p1;
wire  signed [35:0] sext_ln14_7_fu_250_p1;
wire  signed [34:0] grp_fu_364_p3;
wire  signed [34:0] grp_fu_373_p3;
wire  signed [35:0] sext_ln15_8_fu_265_p1;
wire  signed [35:0] sext_ln15_7_fu_262_p1;
wire  signed [34:0] grp_fu_382_p3;
wire  signed [34:0] grp_fu_391_p3;
wire  signed [35:0] sext_ln16_8_fu_277_p1;
wire  signed [35:0] sext_ln16_7_fu_274_p1;
wire   [35:0] s1_fu_256_p2;
wire   [24:0] trunc_ln_fu_286_p4;
wire   [35:0] s2_fu_268_p2;
wire   [24:0] trunc_ln1_fu_300_p4;
wire   [35:0] s3_fu_280_p2;
wire   [24:0] trunc_ln2_fu_314_p4;
wire  signed [25:0] sext_ln18_fu_296_p1;
wire  signed [25:0] sext_ln19_fu_310_p1;
wire  signed [25:0] sext_ln20_fu_324_p1;
wire   [17:0] grp_fu_346_p0;
wire   [17:0] grp_fu_355_p0;
wire   [17:0] grp_fu_364_p0;
wire   [17:0] grp_fu_373_p0;
wire   [17:0] grp_fu_382_p0;
wire   [17:0] grp_fu_391_p0;
reg    grp_fu_346_ce;
reg    grp_fu_355_ce;
reg    grp_fu_364_ce;
reg    grp_fu_373_ce;
reg    grp_fu_382_ce;
reg    grp_fu_391_ce;
reg    ap_ce_reg;
reg  signed [15:0] i_a11_val_int_reg;
reg   [15:0] i_a12_val_int_reg;
reg  signed [15:0] i_a13_val_int_reg;
reg  signed [15:0] i_a21_val_int_reg;
reg   [15:0] i_a22_val_int_reg;
reg  signed [15:0] i_a23_val_int_reg;
reg  signed [15:0] i_a31_val_int_reg;
reg   [15:0] i_a32_val_int_reg;
reg  signed [15:0] i_a33_val_int_reg;
reg   [18:0] i_p1_val_int_reg;
reg   [18:0] i_p2_val_int_reg;
reg   [18:0] i_p3_val_int_reg;
reg   [17:0] i_x_val_int_reg;
reg   [17:0] i_y_val_int_reg;
reg   [17:0] i_z_val_int_reg;
reg   [25:0] ap_return_0_int_reg;
reg   [25:0] ap_return_1_int_reg;
reg   [25:0] ap_return_2_int_reg;

main_process_mul_18ns_16s_34_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 34 ))
mul_18ns_16s_34_1_0_U24(
    .din0(mul_ln14_1_fu_184_p0),
    .din1(i_a12_val_read_reg_430),
    .dout(mul_ln14_1_fu_184_p2)
);

main_process_mul_18ns_16s_34_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 34 ))
mul_18ns_16s_34_1_0_U25(
    .din0(mul_ln15_1_fu_193_p0),
    .din1(i_a22_val_read_reg_425),
    .dout(mul_ln15_1_fu_193_p2)
);

main_process_mul_18ns_16s_34_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 34 ))
mul_18ns_16s_34_1_0_U26(
    .din0(mul_ln16_1_fu_202_p0),
    .din1(i_a32_val_read_reg_420),
    .dout(mul_ln16_1_fu_202_p2)
);

main_process_mac_muladd_18ns_16s_33s_35_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 33 ),
    .dout_WIDTH( 35 ))
mac_muladd_18ns_16s_33s_35_4_0_U27(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_346_p0),
    .din1(i_a11_val_int_reg),
    .din2(shl_ln_fu_211_p3),
    .ce(grp_fu_346_ce),
    .dout(grp_fu_346_p3)
);

main_process_mac_muladd_18ns_16s_34s_35_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 34 ),
    .dout_WIDTH( 35 ))
mac_muladd_18ns_16s_34s_35_4_0_U28(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_355_p0),
    .din1(i_a13_val_int_reg),
    .din2(mul_ln14_1_reg_479),
    .ce(grp_fu_355_ce),
    .dout(grp_fu_355_p3)
);

main_process_mac_muladd_18ns_16s_33s_35_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 33 ),
    .dout_WIDTH( 35 ))
mac_muladd_18ns_16s_33s_35_4_0_U29(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_364_p0),
    .din1(i_a21_val_int_reg),
    .din2(shl_ln1_fu_225_p3),
    .ce(grp_fu_364_ce),
    .dout(grp_fu_364_p3)
);

main_process_mac_muladd_18ns_16s_34s_35_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 34 ),
    .dout_WIDTH( 35 ))
mac_muladd_18ns_16s_34s_35_4_0_U30(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_373_p0),
    .din1(i_a23_val_int_reg),
    .din2(mul_ln15_1_reg_484),
    .ce(grp_fu_373_ce),
    .dout(grp_fu_373_p3)
);

main_process_mac_muladd_18ns_16s_33s_35_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 33 ),
    .dout_WIDTH( 35 ))
mac_muladd_18ns_16s_33s_35_4_0_U31(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_382_p0),
    .din1(i_a31_val_int_reg),
    .din2(shl_ln2_fu_239_p3),
    .ce(grp_fu_382_ce),
    .dout(grp_fu_382_p3)
);

main_process_mac_muladd_18ns_16s_34s_35_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 34 ),
    .dout_WIDTH( 35 ))
mac_muladd_18ns_16s_34s_35_4_0_U32(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_391_p0),
    .din1(i_a33_val_int_reg),
    .din2(mul_ln16_1_reg_489),
    .ce(grp_fu_391_ce),
    .dout(grp_fu_391_p3)
);

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_0_int_reg <= sext_ln18_fu_296_p1;
        ap_return_1_int_reg <= sext_ln19_fu_310_p1;
        ap_return_2_int_reg <= sext_ln20_fu_324_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        i_a11_val_int_reg <= i_a11_val;
        i_a12_val_int_reg <= i_a12_val;
        i_a13_val_int_reg <= i_a13_val;
        i_a21_val_int_reg <= i_a21_val;
        i_a22_val_int_reg <= i_a22_val;
        i_a23_val_int_reg <= i_a23_val;
        i_a31_val_int_reg <= i_a31_val;
        i_a32_val_int_reg <= i_a32_val;
        i_a33_val_int_reg <= i_a33_val;
        i_p1_val_int_reg <= i_p1_val;
        i_p2_val_int_reg <= i_p2_val;
        i_p3_val_int_reg <= i_p3_val;
        i_x_val_int_reg <= i_x_val;
        i_y_val_int_reg <= i_y_val;
        i_z_val_int_reg <= i_z_val;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        i_a12_val_read_reg_430 <= i_a12_val_int_reg;
        i_a22_val_read_reg_425 <= i_a22_val_int_reg;
        i_a32_val_read_reg_420 <= i_a32_val_int_reg;
        i_p1_val_read_reg_415 <= i_p1_val_int_reg;
        i_p1_val_read_reg_415_pp0_iter1_reg <= i_p1_val_read_reg_415;
        i_p2_val_read_reg_410 <= i_p2_val_int_reg;
        i_p2_val_read_reg_410_pp0_iter1_reg <= i_p2_val_read_reg_410;
        i_p3_val_read_reg_405 <= i_p3_val_int_reg;
        i_p3_val_read_reg_405_pp0_iter1_reg <= i_p3_val_read_reg_405;
        i_y_val_read_reg_400 <= i_y_val_int_reg;
        mul_ln14_1_reg_479 <= mul_ln14_1_fu_184_p2;
        mul_ln15_1_reg_484 <= mul_ln15_1_fu_193_p2;
        mul_ln16_1_reg_489 <= mul_ln16_1_fu_202_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_0 = ap_return_0_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_0 = sext_ln18_fu_296_p1;
    end else begin
        ap_return_0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_1 = ap_return_1_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_1 = sext_ln19_fu_310_p1;
    end else begin
        ap_return_1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_2 = ap_return_2_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_2 = sext_ln20_fu_324_p1;
    end else begin
        ap_return_2 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_346_ce = 1'b1;
    end else begin
        grp_fu_346_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_355_ce = 1'b1;
    end else begin
        grp_fu_355_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_364_ce = 1'b1;
    end else begin
        grp_fu_364_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_373_ce = 1'b1;
    end else begin
        grp_fu_373_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_382_ce = 1'b1;
    end else begin
        grp_fu_382_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_391_ce = 1'b1;
    end else begin
        grp_fu_391_ce = 1'b0;
    end
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign grp_fu_346_p0 = zext_ln14_fu_150_p1;

assign grp_fu_355_p0 = zext_ln14_2_fu_158_p1;

assign grp_fu_364_p0 = zext_ln14_fu_150_p1;

assign grp_fu_373_p0 = zext_ln14_2_fu_158_p1;

assign grp_fu_382_p0 = zext_ln14_fu_150_p1;

assign grp_fu_391_p0 = zext_ln14_2_fu_158_p1;

assign mul_ln14_1_fu_184_p0 = zext_ln14_1_fu_181_p1;

assign mul_ln15_1_fu_193_p0 = zext_ln14_1_fu_181_p1;

assign mul_ln16_1_fu_202_p0 = zext_ln14_1_fu_181_p1;

assign s1_fu_256_p2 = ($signed(sext_ln14_8_fu_253_p1) + $signed(sext_ln14_7_fu_250_p1));

assign s2_fu_268_p2 = ($signed(sext_ln15_8_fu_265_p1) + $signed(sext_ln15_7_fu_262_p1));

assign s3_fu_280_p2 = ($signed(sext_ln16_8_fu_277_p1) + $signed(sext_ln16_7_fu_274_p1));

assign sext_ln14_7_fu_250_p1 = grp_fu_346_p3;

assign sext_ln14_8_fu_253_p1 = grp_fu_355_p3;

assign sext_ln15_7_fu_262_p1 = grp_fu_364_p3;

assign sext_ln15_8_fu_265_p1 = grp_fu_373_p3;

assign sext_ln16_7_fu_274_p1 = grp_fu_382_p3;

assign sext_ln16_8_fu_277_p1 = grp_fu_391_p3;

assign sext_ln18_fu_296_p1 = $signed(trunc_ln_fu_286_p4);

assign sext_ln19_fu_310_p1 = $signed(trunc_ln1_fu_300_p4);

assign sext_ln20_fu_324_p1 = $signed(trunc_ln2_fu_314_p4);

assign shl_ln1_fu_225_p3 = {{i_p2_val_read_reg_410_pp0_iter1_reg}, {14'd0}};

assign shl_ln2_fu_239_p3 = {{i_p3_val_read_reg_405_pp0_iter1_reg}, {14'd0}};

assign shl_ln_fu_211_p3 = {{i_p1_val_read_reg_415_pp0_iter1_reg}, {14'd0}};

assign trunc_ln1_fu_300_p4 = {{s2_fu_268_p2[35:11]}};

assign trunc_ln2_fu_314_p4 = {{s3_fu_280_p2[35:11]}};

assign trunc_ln_fu_286_p4 = {{s1_fu_256_p2[35:11]}};

assign zext_ln14_1_fu_181_p1 = i_y_val_read_reg_400;

assign zext_ln14_2_fu_158_p1 = i_z_val_int_reg;

assign zext_ln14_fu_150_p1 = i_x_val_int_reg;

endmodule //main_process_rotate_move
