// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module main_process_triangle (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ap_ce,
        ix_val,
        iy_val,
        test_x_val,
        test_y_val,
        x1_val,
        y1_val,
        x2_val,
        y2_val,
        x3_val,
        y3_val,
        ap_return
);

parameter    ap_ST_fsm_pp0_stage0 = 3'd1;
parameter    ap_ST_fsm_pp0_stage1 = 3'd2;
parameter    ap_ST_fsm_pp0_stage2 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   ap_ce;
input  [13:0] ix_val;
input  [13:0] iy_val;
input  [15:0] test_x_val;
input  [15:0] test_y_val;
input  [15:0] x1_val;
input  [15:0] y1_val;
input  [15:0] x2_val;
input  [15:0] y2_val;
input  [15:0] x3_val;
input  [15:0] y3_val;
output  [8:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage2;
reg    ap_block_pp0_stage2_subdone;
reg   [15:0] y2_val_read_reg_993;
wire    ap_block_pp0_stage0_11001;
reg   [15:0] x2_val_read_reg_999;
reg   [15:0] y1_val_read_reg_1005;
reg   [15:0] x1_val_read_reg_1010;
reg   [15:0] test_y_val_read_reg_1015;
reg   [15:0] test_x_val_read_reg_1021;
wire  signed [15:0] dx1_fu_118_p2;
reg  signed [15:0] dx1_reg_1027;
reg  signed [15:0] dx1_reg_1027_pp0_iter1_reg;
wire   [15:0] dy1_fu_124_p2;
reg  signed [15:0] dy1_reg_1034;
wire  signed [15:0] dy2_fu_130_p2;
reg  signed [15:0] dy2_reg_1039;
reg  signed [15:0] dy2_reg_1039_pp0_iter1_reg;
wire  signed [15:0] dx3_fu_150_p2;
reg  signed [15:0] dx3_reg_1059;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_11001;
wire   [15:0] dy3_fu_155_p2;
reg  signed [15:0] dy3_reg_1066;
wire  signed [15:0] dy4_fu_159_p2;
reg  signed [15:0] dy4_reg_1071;
wire  signed [15:0] dx5_fu_168_p2;
reg  signed [15:0] dx5_reg_1081;
reg  signed [15:0] dx5_reg_1081_pp0_iter1_reg;
wire   [15:0] dy5_fu_173_p2;
reg  signed [15:0] dy5_reg_1088;
wire  signed [15:0] dy6_fu_178_p2;
reg  signed [15:0] dy6_reg_1093;
reg  signed [15:0] dy6_reg_1093_pp0_iter1_reg;
wire   [15:0] dx6_fu_183_p2;
reg  signed [15:0] dx6_reg_1104;
wire   [27:0] mul_ln31_fu_194_p2;
reg  signed [27:0] mul_ln31_reg_1109;
wire   [0:0] x_minus_ok_fu_208_p2;
reg   [0:0] x_minus_ok_reg_1124;
wire    ap_block_pp0_stage2_11001;
reg   [0:0] x_minus_ok_reg_1124_pp0_iter1_reg;
wire   [0:0] x_ok_fu_234_p2;
reg   [0:0] x_ok_reg_1131;
wire   [0:0] x_plus_ok_fu_240_p2;
reg   [0:0] x_plus_ok_reg_1138;
reg   [0:0] x_plus_ok_reg_1138_pp0_iter1_reg;
wire   [0:0] y_minus_ok_fu_246_p2;
reg   [0:0] y_minus_ok_reg_1145;
reg   [0:0] y_minus_ok_reg_1145_pp0_iter1_reg;
wire   [0:0] y_ok_fu_272_p2;
reg   [0:0] y_ok_reg_1152;
wire   [0:0] y_plus_ok_fu_278_p2;
reg   [0:0] y_plus_ok_reg_1159;
reg   [0:0] y_plus_ok_reg_1159_pp0_iter1_reg;
wire   [27:0] mul_ln32_fu_290_p2;
reg  signed [27:0] mul_ln32_reg_1166;
wire  signed [27:0] grp_fu_967_p3;
reg  signed [27:0] sub_ln31_reg_1181;
reg   [15:0] cross1_r5_reg_1186;
wire   [27:0] mul_ln33_fu_317_p2;
reg  signed [27:0] mul_ln33_reg_1194;
reg   [0:0] sign2_r5_reg_1199;
reg   [0:0] sign2_r1_reg_1205;
reg   [0:0] sign2_r2_reg_1211;
reg   [0:0] sign2_r3_reg_1217;
reg   [0:0] sign2_r4_reg_1223;
reg   [0:0] sign2_r6_reg_1229;
reg   [0:0] sign2_r7_reg_1235;
reg   [0:0] sign2_r8_reg_1241;
reg   [0:0] sign2_r9_reg_1247;
wire   [15:0] cross1_r2_fu_452_p2;
reg   [15:0] cross1_r2_reg_1253;
wire   [15:0] cross3_r2_fu_456_p2;
reg   [15:0] cross3_r2_reg_1259;
wire   [15:0] cross1_r8_fu_479_p2;
reg   [15:0] cross1_r8_reg_1265;
wire   [15:0] cross3_r8_fu_483_p2;
reg   [15:0] cross3_r8_reg_1271;
wire   [0:0] and_ln156_fu_681_p2;
reg   [0:0] and_ln156_reg_1277;
wire   [0:0] and_ln158_fu_691_p2;
reg   [0:0] and_ln158_reg_1282;
wire   [0:0] and_ln159_fu_701_p2;
reg   [0:0] and_ln159_reg_1287;
wire   [0:0] and_ln160_fu_711_p2;
reg   [0:0] and_ln160_reg_1292;
wire   [0:0] and_ln162_fu_721_p2;
reg   [0:0] and_ln162_reg_1297;
reg    ap_enable_reg_pp0_iter0_reg;
reg    ap_block_pp0_stage0_subdone;
reg   [13:0] ap_port_reg_ix_val;
reg   [13:0] ap_port_reg_iy_val;
reg   [15:0] ap_port_reg_x3_val;
reg   [15:0] ap_port_reg_y3_val;
wire    ap_block_pp0_stage0;
wire  signed [15:0] dx2_fu_136_p2;
wire    ap_block_pp0_stage1;
wire  signed [15:0] dx4_fu_164_p2;
wire    ap_block_pp0_stage2;
wire   [0:0] tmp_fu_214_p3;
wire   [0:0] icmp_ln22_fu_228_p2;
wire   [0:0] xor_ln22_fu_222_p2;
wire   [0:0] tmp_1_fu_252_p3;
wire   [0:0] icmp_ln26_fu_266_p2;
wire   [0:0] xor_ln26_fu_260_p2;
wire  signed [27:0] grp_fu_975_p3;
wire   [15:0] cross2_r5_fu_323_p4;
wire   [15:0] cross2_r2_fu_332_p2;
wire   [15:0] cross2_r8_fu_357_p2;
wire   [15:0] cross2_r1_fu_337_p2;
wire   [15:0] cross2_r3_fu_342_p2;
wire   [15:0] cross2_r4_fu_347_p2;
wire   [15:0] cross2_r6_fu_352_p2;
wire   [15:0] cross2_r7_fu_362_p2;
wire   [15:0] cross2_r9_fu_367_p2;
wire  signed [27:0] grp_fu_984_p3;
wire   [15:0] cross3_r5_fu_443_p4;
wire   [0:0] sign1_r5_fu_488_p3;
wire   [0:0] sign3_r5_fu_495_p3;
wire   [0:0] xor_ln84_fu_502_p2;
wire   [0:0] xor_ln84_1_fu_507_p2;
wire   [0:0] or_ln84_fu_512_p2;
wire   [0:0] sign1_r2_fu_524_p3;
wire   [0:0] sign3_r2_fu_532_p3;
wire   [0:0] xor_ln96_fu_540_p2;
wire   [0:0] xor_ln96_1_fu_545_p2;
wire   [0:0] or_ln96_fu_550_p2;
wire   [15:0] cross1_r4_fu_461_p2;
wire   [15:0] cross3_r4_fu_465_p2;
wire   [0:0] sign1_r4_fu_562_p3;
wire   [0:0] sign3_r4_fu_570_p3;
wire   [0:0] xor_ln110_fu_578_p2;
wire   [0:0] xor_ln110_1_fu_583_p2;
wire   [0:0] or_ln110_fu_588_p2;
wire   [15:0] cross1_r6_fu_470_p2;
wire   [15:0] cross3_r6_fu_474_p2;
wire   [0:0] sign1_r6_fu_600_p3;
wire   [0:0] sign3_r6_fu_608_p3;
wire   [0:0] xor_ln117_fu_616_p2;
wire   [0:0] xor_ln117_1_fu_621_p2;
wire   [0:0] or_ln117_fu_626_p2;
wire   [0:0] sign1_r8_fu_638_p3;
wire   [0:0] sign3_r8_fu_646_p3;
wire   [0:0] xor_ln131_fu_654_p2;
wire   [0:0] xor_ln131_1_fu_659_p2;
wire   [0:0] or_ln131_fu_664_p2;
wire   [0:0] inside_r8_fu_670_p2;
wire   [0:0] and_ln156_1_fu_676_p2;
wire   [0:0] inside_r4_fu_594_p2;
wire   [0:0] and_ln158_1_fu_686_p2;
wire   [0:0] inside_r5_fu_518_p2;
wire   [0:0] and_ln159_1_fu_696_p2;
wire   [0:0] inside_r6_fu_632_p2;
wire   [0:0] and_ln160_1_fu_706_p2;
wire   [0:0] inside_r2_fu_556_p2;
wire   [0:0] and_ln162_1_fu_716_p2;
wire   [15:0] cross1_r1_fu_726_p2;
wire   [15:0] cross3_r1_fu_730_p2;
wire   [0:0] sign1_r1_fu_758_p3;
wire   [0:0] sign3_r1_fu_766_p3;
wire   [0:0] xor_ln90_fu_774_p2;
wire   [0:0] xor_ln90_1_fu_779_p2;
wire   [0:0] or_ln90_fu_784_p2;
wire   [15:0] cross1_r3_fu_734_p2;
wire   [15:0] cross3_r3_fu_738_p2;
wire   [0:0] sign1_r3_fu_796_p3;
wire   [0:0] sign3_r3_fu_804_p3;
wire   [0:0] xor_ln103_fu_812_p2;
wire   [0:0] xor_ln103_1_fu_817_p2;
wire   [0:0] or_ln103_fu_822_p2;
wire   [15:0] cross1_r7_fu_742_p2;
wire   [15:0] cross3_r7_fu_746_p2;
wire   [0:0] sign1_r7_fu_834_p3;
wire   [0:0] sign3_r7_fu_842_p3;
wire   [0:0] xor_ln124_fu_850_p2;
wire   [0:0] xor_ln124_1_fu_855_p2;
wire   [0:0] or_ln124_fu_860_p2;
wire   [15:0] cross1_r9_fu_750_p2;
wire   [15:0] cross3_r9_fu_754_p2;
wire   [0:0] sign1_r9_fu_872_p3;
wire   [0:0] sign3_r9_fu_880_p3;
wire   [0:0] xor_ln138_fu_888_p2;
wire   [0:0] xor_ln138_1_fu_893_p2;
wire   [0:0] or_ln138_fu_898_p2;
wire   [0:0] inside_r7_fu_866_p2;
wire   [0:0] and_ln155_1_fu_910_p2;
wire   [0:0] inside_r9_fu_904_p2;
wire   [0:0] and_ln157_1_fu_920_p2;
wire   [0:0] inside_r1_fu_790_p2;
wire   [0:0] and_ln161_1_fu_930_p2;
wire   [0:0] inside_r3_fu_828_p2;
wire   [0:0] and_ln163_1_fu_940_p2;
wire   [0:0] and_ln163_fu_945_p2;
wire   [0:0] and_ln161_fu_935_p2;
wire   [0:0] and_ln157_fu_925_p2;
wire   [0:0] and_ln155_fu_915_p2;
reg    grp_fu_967_ce;
reg    grp_fu_975_ce;
reg    grp_fu_984_ce;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0_0to1;
reg    ap_reset_idle_pp0;
reg    ap_idle_pp0_1to2;
reg    ap_block_pp0_stage1_subdone;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
end

main_process_mul_16s_16s_28_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 28 ))
mul_16s_16s_28_1_1_U63(
    .din0(dx1_reg_1027),
    .din1(dy1_reg_1034),
    .dout(mul_ln31_fu_194_p2)
);

main_process_mul_16s_16s_28_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 28 ))
mul_16s_16s_28_1_1_U64(
    .din0(dx3_reg_1059),
    .din1(dy3_reg_1066),
    .dout(mul_ln32_fu_290_p2)
);

main_process_mul_16s_16s_28_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 28 ))
mul_16s_16s_28_1_1_U65(
    .din0(dy5_reg_1088),
    .din1(dx5_reg_1081),
    .dout(mul_ln33_fu_317_p2)
);

main_process_mac_mulsub_16s_16s_28s_28_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 28 ),
    .dout_WIDTH( 28 ))
mac_mulsub_16s_16s_28s_28_4_1_U66(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(dy2_fu_130_p2),
    .din1(dx2_fu_136_p2),
    .din2(mul_ln31_reg_1109),
    .ce(grp_fu_967_ce),
    .dout(grp_fu_967_p3)
);

main_process_mac_mulsub_16s_16s_28s_28_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 28 ),
    .dout_WIDTH( 28 ))
mac_mulsub_16s_16s_28s_28_4_1_U67(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(dy4_fu_159_p2),
    .din1(dx4_fu_164_p2),
    .din2(mul_ln32_reg_1166),
    .ce(grp_fu_975_ce),
    .dout(grp_fu_975_p3)
);

main_process_mac_mulsub_16s_16s_28s_28_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 28 ),
    .dout_WIDTH( 28 ))
mac_mulsub_16s_16s_28s_28_4_1_U68(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(dy6_reg_1093),
    .din1(dx6_reg_1104),
    .din2(mul_ln33_reg_1194),
    .ce(grp_fu_984_ce),
    .dout(grp_fu_984_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        and_ln156_reg_1277 <= and_ln156_fu_681_p2;
        and_ln158_reg_1282 <= and_ln158_fu_691_p2;
        and_ln159_reg_1287 <= and_ln159_fu_701_p2;
        and_ln160_reg_1292 <= and_ln160_fu_711_p2;
        and_ln162_reg_1297 <= and_ln162_fu_721_p2;
        cross1_r2_reg_1253 <= cross1_r2_fu_452_p2;
        cross1_r8_reg_1265 <= cross1_r8_fu_479_p2;
        cross3_r2_reg_1259 <= cross3_r2_fu_456_p2;
        cross3_r8_reg_1271 <= cross3_r8_fu_483_p2;
        mul_ln32_reg_1166 <= mul_ln32_fu_290_p2;
        x_minus_ok_reg_1124 <= x_minus_ok_fu_208_p2;
        x_minus_ok_reg_1124_pp0_iter1_reg <= x_minus_ok_reg_1124;
        x_ok_reg_1131 <= x_ok_fu_234_p2;
        x_plus_ok_reg_1138 <= x_plus_ok_fu_240_p2;
        x_plus_ok_reg_1138_pp0_iter1_reg <= x_plus_ok_reg_1138;
        y_minus_ok_reg_1145 <= y_minus_ok_fu_246_p2;
        y_minus_ok_reg_1145_pp0_iter1_reg <= y_minus_ok_reg_1145;
        y_ok_reg_1152 <= y_ok_fu_272_p2;
        y_plus_ok_reg_1159 <= y_plus_ok_fu_278_p2;
        y_plus_ok_reg_1159_pp0_iter1_reg <= y_plus_ok_reg_1159;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_port_reg_ix_val <= ix_val;
        ap_port_reg_iy_val <= iy_val;
        ap_port_reg_x3_val <= x3_val;
        ap_port_reg_y3_val <= y3_val;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        cross1_r5_reg_1186 <= {{grp_fu_967_p3[27:12]}};
        dx1_reg_1027 <= dx1_fu_118_p2;
        dx1_reg_1027_pp0_iter1_reg <= dx1_reg_1027;
        dy1_reg_1034 <= dy1_fu_124_p2;
        dy2_reg_1039 <= dy2_fu_130_p2;
        dy2_reg_1039_pp0_iter1_reg <= dy2_reg_1039;
        mul_ln33_reg_1194 <= mul_ln33_fu_317_p2;
        test_x_val_read_reg_1021 <= test_x_val;
        test_y_val_read_reg_1015 <= test_y_val;
        x1_val_read_reg_1010 <= x1_val;
        x2_val_read_reg_999 <= x2_val;
        y1_val_read_reg_1005 <= y1_val;
        y2_val_read_reg_993 <= y2_val;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_ce))) begin
        dx3_reg_1059 <= dx3_fu_150_p2;
        dx5_reg_1081 <= dx5_fu_168_p2;
        dx5_reg_1081_pp0_iter1_reg <= dx5_reg_1081;
        dx6_reg_1104 <= dx6_fu_183_p2;
        dy3_reg_1066 <= dy3_fu_155_p2;
        dy4_reg_1071 <= dy4_fu_159_p2;
        dy5_reg_1088 <= dy5_fu_173_p2;
        dy6_reg_1093 <= dy6_fu_178_p2;
        dy6_reg_1093_pp0_iter1_reg <= dy6_reg_1093;
        mul_ln31_reg_1109 <= mul_ln31_fu_194_p2;
        sign2_r1_reg_1205 <= cross2_r1_fu_337_p2[32'd15];
        sign2_r2_reg_1211 <= cross2_r2_fu_332_p2[32'd15];
        sign2_r3_reg_1217 <= cross2_r3_fu_342_p2[32'd15];
        sign2_r4_reg_1223 <= cross2_r4_fu_347_p2[32'd15];
        sign2_r5_reg_1199 <= grp_fu_975_p3[32'd27];
        sign2_r6_reg_1229 <= cross2_r6_fu_352_p2[32'd15];
        sign2_r7_reg_1235 <= cross2_r7_fu_362_p2[32'd15];
        sign2_r8_reg_1241 <= cross2_r8_fu_357_p2[32'd15];
        sign2_r9_reg_1247 <= cross2_r9_fu_367_p2[32'd15];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sub_ln31_reg_1181 <= grp_fu_967_p3;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to1 = 1'b1;
    end else begin
        ap_idle_pp0_0to1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to2 = 1'b1;
    end else begin
        ap_idle_pp0_1to2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to1 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))))) begin
        grp_fu_967_ce = 1'b1;
    end else begin
        grp_fu_967_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))))) begin
        grp_fu_975_ce = 1'b1;
    end else begin
        grp_fu_975_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))))) begin
        grp_fu_984_ce = 1'b1;
    end else begin
        grp_fu_984_ce = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start == 1'b0) & (ap_idle_pp0_1to2 == 1'b1)) & (ap_reset_idle_pp0 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else if (((ap_reset_idle_pp0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign and_ln155_1_fu_910_p2 = (y_minus_ok_reg_1145_pp0_iter1_reg & inside_r7_fu_866_p2);

assign and_ln155_fu_915_p2 = (x_minus_ok_reg_1124_pp0_iter1_reg & and_ln155_1_fu_910_p2);

assign and_ln156_1_fu_676_p2 = (y_minus_ok_reg_1145 & inside_r8_fu_670_p2);

assign and_ln156_fu_681_p2 = (x_ok_reg_1131 & and_ln156_1_fu_676_p2);

assign and_ln157_1_fu_920_p2 = (y_minus_ok_reg_1145_pp0_iter1_reg & inside_r9_fu_904_p2);

assign and_ln157_fu_925_p2 = (x_plus_ok_reg_1138_pp0_iter1_reg & and_ln157_1_fu_920_p2);

assign and_ln158_1_fu_686_p2 = (y_ok_reg_1152 & inside_r4_fu_594_p2);

assign and_ln158_fu_691_p2 = (x_minus_ok_reg_1124 & and_ln158_1_fu_686_p2);

assign and_ln159_1_fu_696_p2 = (y_ok_reg_1152 & inside_r5_fu_518_p2);

assign and_ln159_fu_701_p2 = (x_ok_reg_1131 & and_ln159_1_fu_696_p2);

assign and_ln160_1_fu_706_p2 = (y_ok_reg_1152 & inside_r6_fu_632_p2);

assign and_ln160_fu_711_p2 = (x_plus_ok_reg_1138 & and_ln160_1_fu_706_p2);

assign and_ln161_1_fu_930_p2 = (y_plus_ok_reg_1159_pp0_iter1_reg & inside_r1_fu_790_p2);

assign and_ln161_fu_935_p2 = (x_minus_ok_reg_1124_pp0_iter1_reg & and_ln161_1_fu_930_p2);

assign and_ln162_1_fu_716_p2 = (y_plus_ok_reg_1159 & inside_r2_fu_556_p2);

assign and_ln162_fu_721_p2 = (x_ok_reg_1131 & and_ln162_1_fu_716_p2);

assign and_ln163_1_fu_940_p2 = (y_plus_ok_reg_1159_pp0_iter1_reg & inside_r3_fu_828_p2);

assign and_ln163_fu_945_p2 = (x_plus_ok_reg_1138_pp0_iter1_reg & and_ln163_1_fu_940_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (1'b0 == ap_ce);
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone = (1'b0 == ap_ce);
end

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_subdone = (1'b0 == ap_ce);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_return = {{{{{{{{{and_ln163_fu_945_p2}, {and_ln162_reg_1297}}, {and_ln161_fu_935_p2}}, {and_ln160_reg_1292}}, {and_ln159_reg_1287}}, {and_ln158_reg_1282}}, {and_ln157_fu_925_p2}}, {and_ln156_reg_1277}}, {and_ln155_fu_915_p2}};

assign cross1_r1_fu_726_p2 = ($signed(cross1_r2_reg_1253) + $signed(dy2_reg_1039_pp0_iter1_reg));

assign cross1_r2_fu_452_p2 = ($signed(cross1_r5_reg_1186) + $signed(dx1_reg_1027_pp0_iter1_reg));

assign cross1_r3_fu_734_p2 = ($signed(cross1_r2_reg_1253) - $signed(dy2_reg_1039_pp0_iter1_reg));

assign cross1_r4_fu_461_p2 = ($signed(cross1_r5_reg_1186) + $signed(dy2_reg_1039_pp0_iter1_reg));

assign cross1_r6_fu_470_p2 = ($signed(cross1_r5_reg_1186) - $signed(dy2_reg_1039_pp0_iter1_reg));

assign cross1_r7_fu_742_p2 = ($signed(cross1_r8_reg_1265) + $signed(dy2_reg_1039_pp0_iter1_reg));

assign cross1_r8_fu_479_p2 = ($signed(cross1_r5_reg_1186) - $signed(dx1_reg_1027_pp0_iter1_reg));

assign cross1_r9_fu_750_p2 = ($signed(cross1_r8_reg_1265) - $signed(dy2_reg_1039_pp0_iter1_reg));

assign cross2_r1_fu_337_p2 = ($signed(cross2_r2_fu_332_p2) + $signed(dy4_reg_1071));

assign cross2_r2_fu_332_p2 = ($signed(cross2_r5_fu_323_p4) + $signed(dx3_reg_1059));

assign cross2_r3_fu_342_p2 = ($signed(cross2_r2_fu_332_p2) - $signed(dy4_reg_1071));

assign cross2_r4_fu_347_p2 = ($signed(cross2_r5_fu_323_p4) + $signed(dy4_reg_1071));

assign cross2_r5_fu_323_p4 = {{grp_fu_975_p3[27:12]}};

assign cross2_r6_fu_352_p2 = ($signed(cross2_r5_fu_323_p4) - $signed(dy4_reg_1071));

assign cross2_r7_fu_362_p2 = ($signed(cross2_r8_fu_357_p2) + $signed(dy4_reg_1071));

assign cross2_r8_fu_357_p2 = ($signed(cross2_r5_fu_323_p4) - $signed(dx3_reg_1059));

assign cross2_r9_fu_367_p2 = ($signed(cross2_r8_fu_357_p2) - $signed(dy4_reg_1071));

assign cross3_r1_fu_730_p2 = ($signed(cross3_r2_reg_1259) + $signed(dy6_reg_1093_pp0_iter1_reg));

assign cross3_r2_fu_456_p2 = ($signed(cross3_r5_fu_443_p4) + $signed(dx5_reg_1081_pp0_iter1_reg));

assign cross3_r3_fu_738_p2 = ($signed(cross3_r2_reg_1259) - $signed(dy6_reg_1093_pp0_iter1_reg));

assign cross3_r4_fu_465_p2 = ($signed(cross3_r5_fu_443_p4) + $signed(dy6_reg_1093_pp0_iter1_reg));

assign cross3_r5_fu_443_p4 = {{grp_fu_984_p3[27:12]}};

assign cross3_r6_fu_474_p2 = ($signed(cross3_r5_fu_443_p4) - $signed(dy6_reg_1093_pp0_iter1_reg));

assign cross3_r7_fu_746_p2 = ($signed(cross3_r8_reg_1271) + $signed(dy6_reg_1093_pp0_iter1_reg));

assign cross3_r8_fu_483_p2 = ($signed(cross3_r5_fu_443_p4) - $signed(dx5_reg_1081_pp0_iter1_reg));

assign cross3_r9_fu_754_p2 = ($signed(cross3_r8_reg_1271) - $signed(dy6_reg_1093_pp0_iter1_reg));

assign dx1_fu_118_p2 = (x2_val - x1_val);

assign dx2_fu_136_p2 = (test_x_val - x1_val);

assign dx3_fu_150_p2 = (ap_port_reg_x3_val - x2_val_read_reg_999);

assign dx4_fu_164_p2 = (test_x_val_read_reg_1021 - x2_val_read_reg_999);

assign dx5_fu_168_p2 = (x1_val_read_reg_1010 - ap_port_reg_x3_val);

assign dx6_fu_183_p2 = (test_x_val_read_reg_1021 - ap_port_reg_x3_val);

assign dy1_fu_124_p2 = (test_y_val - y1_val);

assign dy2_fu_130_p2 = (y2_val - y1_val);

assign dy3_fu_155_p2 = (test_y_val_read_reg_1015 - y2_val_read_reg_993);

assign dy4_fu_159_p2 = (ap_port_reg_y3_val - y2_val_read_reg_993);

assign dy5_fu_173_p2 = (test_y_val_read_reg_1015 - ap_port_reg_y3_val);

assign dy6_fu_178_p2 = (y1_val_read_reg_1005 - ap_port_reg_y3_val);

assign icmp_ln22_fu_228_p2 = (($signed(ap_port_reg_ix_val) < $signed(14'd385)) ? 1'b1 : 1'b0);

assign icmp_ln26_fu_266_p2 = (($signed(ap_port_reg_iy_val) < $signed(14'd385)) ? 1'b1 : 1'b0);

assign inside_r1_fu_790_p2 = (or_ln90_fu_784_p2 ^ 1'd1);

assign inside_r2_fu_556_p2 = (or_ln96_fu_550_p2 ^ 1'd1);

assign inside_r3_fu_828_p2 = (or_ln103_fu_822_p2 ^ 1'd1);

assign inside_r4_fu_594_p2 = (or_ln110_fu_588_p2 ^ 1'd1);

assign inside_r5_fu_518_p2 = (or_ln84_fu_512_p2 ^ 1'd1);

assign inside_r6_fu_632_p2 = (or_ln117_fu_626_p2 ^ 1'd1);

assign inside_r7_fu_866_p2 = (or_ln124_fu_860_p2 ^ 1'd1);

assign inside_r8_fu_670_p2 = (or_ln131_fu_664_p2 ^ 1'd1);

assign inside_r9_fu_904_p2 = (or_ln138_fu_898_p2 ^ 1'd1);

assign or_ln103_fu_822_p2 = (xor_ln103_fu_812_p2 | xor_ln103_1_fu_817_p2);

assign or_ln110_fu_588_p2 = (xor_ln110_fu_578_p2 | xor_ln110_1_fu_583_p2);

assign or_ln117_fu_626_p2 = (xor_ln117_fu_616_p2 | xor_ln117_1_fu_621_p2);

assign or_ln124_fu_860_p2 = (xor_ln124_fu_850_p2 | xor_ln124_1_fu_855_p2);

assign or_ln131_fu_664_p2 = (xor_ln131_fu_654_p2 | xor_ln131_1_fu_659_p2);

assign or_ln138_fu_898_p2 = (xor_ln138_fu_888_p2 | xor_ln138_1_fu_893_p2);

assign or_ln84_fu_512_p2 = (xor_ln84_fu_502_p2 | xor_ln84_1_fu_507_p2);

assign or_ln90_fu_784_p2 = (xor_ln90_fu_774_p2 | xor_ln90_1_fu_779_p2);

assign or_ln96_fu_550_p2 = (xor_ln96_fu_540_p2 | xor_ln96_1_fu_545_p2);

assign sign1_r1_fu_758_p3 = cross1_r1_fu_726_p2[32'd15];

assign sign1_r2_fu_524_p3 = cross1_r2_fu_452_p2[32'd15];

assign sign1_r3_fu_796_p3 = cross1_r3_fu_734_p2[32'd15];

assign sign1_r4_fu_562_p3 = cross1_r4_fu_461_p2[32'd15];

assign sign1_r5_fu_488_p3 = sub_ln31_reg_1181[32'd27];

assign sign1_r6_fu_600_p3 = cross1_r6_fu_470_p2[32'd15];

assign sign1_r7_fu_834_p3 = cross1_r7_fu_742_p2[32'd15];

assign sign1_r8_fu_638_p3 = cross1_r8_fu_479_p2[32'd15];

assign sign1_r9_fu_872_p3 = cross1_r9_fu_750_p2[32'd15];

assign sign3_r1_fu_766_p3 = cross3_r1_fu_730_p2[32'd15];

assign sign3_r2_fu_532_p3 = cross3_r2_fu_456_p2[32'd15];

assign sign3_r3_fu_804_p3 = cross3_r3_fu_738_p2[32'd15];

assign sign3_r4_fu_570_p3 = cross3_r4_fu_465_p2[32'd15];

assign sign3_r5_fu_495_p3 = grp_fu_984_p3[32'd27];

assign sign3_r6_fu_608_p3 = cross3_r6_fu_474_p2[32'd15];

assign sign3_r7_fu_842_p3 = cross3_r7_fu_746_p2[32'd15];

assign sign3_r8_fu_646_p3 = cross3_r8_fu_483_p2[32'd15];

assign sign3_r9_fu_880_p3 = cross3_r9_fu_754_p2[32'd15];

assign tmp_1_fu_252_p3 = ap_port_reg_iy_val[32'd13];

assign tmp_fu_214_p3 = ap_port_reg_ix_val[32'd13];

assign x_minus_ok_fu_208_p2 = (($signed(ap_port_reg_ix_val) > $signed(14'd0)) ? 1'b1 : 1'b0);

assign x_ok_fu_234_p2 = (xor_ln22_fu_222_p2 & icmp_ln22_fu_228_p2);

assign x_plus_ok_fu_240_p2 = (($signed(ap_port_reg_ix_val) < $signed(14'd384)) ? 1'b1 : 1'b0);

assign xor_ln103_1_fu_817_p2 = (sign3_r3_fu_804_p3 ^ sign2_r3_reg_1217);

assign xor_ln103_fu_812_p2 = (sign2_r3_reg_1217 ^ sign1_r3_fu_796_p3);

assign xor_ln110_1_fu_583_p2 = (sign3_r4_fu_570_p3 ^ sign2_r4_reg_1223);

assign xor_ln110_fu_578_p2 = (sign2_r4_reg_1223 ^ sign1_r4_fu_562_p3);

assign xor_ln117_1_fu_621_p2 = (sign3_r6_fu_608_p3 ^ sign2_r6_reg_1229);

assign xor_ln117_fu_616_p2 = (sign2_r6_reg_1229 ^ sign1_r6_fu_600_p3);

assign xor_ln124_1_fu_855_p2 = (sign3_r7_fu_842_p3 ^ sign2_r7_reg_1235);

assign xor_ln124_fu_850_p2 = (sign2_r7_reg_1235 ^ sign1_r7_fu_834_p3);

assign xor_ln131_1_fu_659_p2 = (sign3_r8_fu_646_p3 ^ sign2_r8_reg_1241);

assign xor_ln131_fu_654_p2 = (sign2_r8_reg_1241 ^ sign1_r8_fu_638_p3);

assign xor_ln138_1_fu_893_p2 = (sign3_r9_fu_880_p3 ^ sign2_r9_reg_1247);

assign xor_ln138_fu_888_p2 = (sign2_r9_reg_1247 ^ sign1_r9_fu_872_p3);

assign xor_ln22_fu_222_p2 = (tmp_fu_214_p3 ^ 1'd1);

assign xor_ln26_fu_260_p2 = (tmp_1_fu_252_p3 ^ 1'd1);

assign xor_ln84_1_fu_507_p2 = (sign3_r5_fu_495_p3 ^ sign2_r5_reg_1199);

assign xor_ln84_fu_502_p2 = (sign2_r5_reg_1199 ^ sign1_r5_fu_488_p3);

assign xor_ln90_1_fu_779_p2 = (sign3_r1_fu_766_p3 ^ sign2_r1_reg_1205);

assign xor_ln90_fu_774_p2 = (sign2_r1_reg_1205 ^ sign1_r1_fu_758_p3);

assign xor_ln96_1_fu_545_p2 = (sign3_r2_fu_532_p3 ^ sign2_r2_reg_1211);

assign xor_ln96_fu_540_p2 = (sign2_r2_reg_1211 ^ sign1_r2_fu_524_p3);

assign y_minus_ok_fu_246_p2 = (($signed(ap_port_reg_iy_val) > $signed(14'd0)) ? 1'b1 : 1'b0);

assign y_ok_fu_272_p2 = (xor_ln26_fu_260_p2 & icmp_ln26_fu_266_p2);

assign y_plus_ok_fu_278_p2 = (($signed(ap_port_reg_iy_val) < $signed(14'd384)) ? 1'b1 : 1'b0);

endmodule //main_process_triangle
